/**
 * Re-export knowledge contracts from @divine/types for the web app.
 */
export {
  PRIMARY_WORKS,
  CONFIDENCE_LEVELS,
  CONFIDENCE_LABELS,
  scriptureReferenceSchema,
  formatCitation,
  ENTITY_KINDS,
  ENTITY_KIND_LABELS,
  ENTITY_KIND_ROUTE,
  ENTITY_KIND_TOKENS,
  GENDERS,
  ERAS,
  ENTITY_STATUSES,
  knowledgeEntitySchema,
  knowledgeEntityCollectionSchema,
  entitySearchKeys,
  entityAtlasSchema,
  EVENT_TYPES,
  EVENT_TYPE_LABELS,
  entityEventSchema,
  entityConceptSchema,
  WEAPON_CATEGORIES,
  WEAPON_CATEGORY_LABELS,
  WEAPON_FOCUS,
  WEAPON_FOCUS_LABELS,
  entityWeaponSchema,
  RELATION_TYPES,
  RELATION_TYPE_LABELS,
  PARENT_EDGE_TYPES,
  CHILD_TO_PARENT_EDGE_TYPES,
  RULE_EDGE_TYPES,
  BATTLE_EDGE_TYPES,
  LOCATION_EDGE_TYPES,
  SYMMETRIC_RELATION_TYPES,
  RELATION_INVERSES,
  knowledgeRelationSchema,
  knowledgeRelationCollectionSchema,
  makeRelationId,
  toRelationshipObject,
  relationDedupeKey,
  dedupeRelations,
  isParentToChildType,
  isChildToParentType,
  COLLECTION_KINDS,
  COLLECTION_STATUSES,
  knowledgeCollectionSchema,
  knowledgeCollectionBundleSchema,
  RELATED_CONTENT_BUCKETS,
  RELATED_CONTENT_BUCKET_LABELS,
  ENTITY_KIND_BUCKETS,
  RELATION_TYPE_WEIGHTS,
  classifyRelatedBuckets,
  relationTypeWeight,
  confidenceWeight,
  scoreRelatedHop,
  buildRelatedContent,
  atlasRouteSchema,
  atlasRouteBundleSchema,
  atlasDatasetSchema,
  atlasPolygonSchema,
  atlasLayerSchema,
  DEFAULT_ATLAS_PROJECTION,
  DEFAULT_ATLAS_LAYERS,
  buildAtlasScene,
  type ConfidenceLevel,
  type ScriptureReference,
  type EntityKind,
  type Gender,
  type Era,
  type EntityStatus,
  type KnowledgeEntity,
  type KnowledgeEntityCollection,
  type EntityAtlas,
  type EventType,
  type EntityEvent,
  type EntityConcept,
  type WeaponCategory,
  type WeaponFocus,
  type EntityWeapon,
  type RelationType,
  type KnowledgeRelation,
  type KnowledgeRelationCollection,
  type RelationshipObject,
  type CollectionKind,
  type CollectionStatus,
  type KnowledgeCollection,
  type KnowledgeCollectionBundle,
  type VariantTradition,
  type RelatedContentBucket,
  type RelatedContentEntity,
  type RelatedContentOptions,
  type RelatedContentHit,
  type RelatedChapterHit,
  type RelatedContentBucketGroup,
  type RelatedContentResult,
  type AtlasRoute,
  type AtlasRouteBundle,
  type AtlasDataset,
  type AtlasPolygon,
  type AtlasLayer,
  type AtlasPlaceCategory,
  type AtlasScene,
  NAME_CLASSIFICATIONS,
  NAME_CLASSIFICATION_LABELS,
  NAME_GENDERS,
  scriptureCitationSchema,
  babyNameMeaningsSchema,
  babyNameEtymologySchema,
  babyNameRecordSchema,
  babyNameCollectionSchema,
  type NameClassification,
  type NameGenderUsage,
  type ScriptureCitation,
  type BabyNameMeanings,
  type BabyNameEtymology,
  type BabyNameRecord,
  type BabyNameCollection,
} from "@divine/types";

