/**
 * Solar / Lunar / Raghu / Yadu / Kuru / Pāṇḍava / Kaurava / Rāma / Kṛṣṇa
 * — sparse, citation-first spines. Accuracy over completeness.
 */
import { BP, VP, MB, RM, HV, BG, rel } from "./cites.mts";
import { type PersonDraft } from "./people-cosmic.mts";

function p(draft: PersonDraft): PersonDraft {
  return {
    ...draft,
    iastName: draft.iastName ?? draft.name,
    aliases: draft.aliases ?? [],
    importance: draft.importance ?? 3,
    relationships: draft.relationships ?? [],
    scriptureSources: draft.scriptureSources ?? [],
  };
}

/** Manus */
export const MANUS: PersonDraft[] = [
  p({
    id: "vaivasvata-manu",
    name: "Vaivasvata Manu",
    englishName: "Vaivasvata Manu",
    sanskritName: "वैवस्वत मनु",
    aliases: ["Manu", "Sraddhadeva", "Śrāddhadeva", "Satyavrata"],
    gender: "male",
    category: "manu",
    era: "satya-yuga",
    dynasty: "suryavamsa",
    epithet: "Current Manu; son of Vivasvān; father of Ikṣvāku",
    description:
      "Vaivasvata Manu, son of Vivasvān, is the Manu of the present manvantara. From him descends Ikṣvāku and the Solar Dynasty. The Bhāgavata preserves the flood narrative of this Manu.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "vivasvan", "verified", [BP("8", "24"), VP("3", "1"), BG("4")]),
      rel("son", "ikshvaku", "verified", [BP("9", "6"), VP("4", "1"), RM("Bāla Kāṇḍa", "70")]),
    ],
    scriptureSources: [BP("8", "24"), BP("9", "1–6"), VP("3", "1")],
    relatedVerses: [{ workCode: "bg", publicId: "bg.4.1", label: "Vivasvān taught Manu" }],
  }),
];

/** Solar Dynasty spine (Sūryavaṃśa / Ikṣvāku) */
export const SOLAR: PersonDraft[] = [
  p({
    id: "ikshvaku",
    name: "Ikṣvāku",
    englishName: "Ikshvaku",
    sanskritName: "इक्ष्वाकु",
    gender: "male",
    category: "dynasty-founder",
    era: "satya-yuga",
    dynasty: "suryavamsa",
    epithet: "Founder of the Ikṣvāku (Solar) line",
    description: "Ikṣvāku, son of Vaivasvata Manu, is the eponymous founder of the Solar Dynasty of Ayodhyā.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "vaivasvata-manu", "verified", [BP("9", "6"), VP("4", "1")]),
      rel("descendant", "raghu", "traditional", [BP("9", "9–10"), RM("Bāla Kāṇḍa", "70")], "Many generations intervene; Raghu stands later in the Ikṣvāku line."),
    ],
    scriptureSources: [BP("9", "6"), VP("4", "1")],
  }),
  p({
    id: "raghu",
    name: "Raghu",
    englishName: "Raghu",
    sanskritName: "रघु",
    gender: "male",
    category: "king",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Eponym of the Raghuvaṃśa",
    description: "Raghu is a celebrated Ikṣvāku king; the Raghuvaṃśa takes its name from him. Daśaratha and Rāma descend in his line.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    relationships: [
      rel("ancestor", "ikshvaku", "traditional", [BP("9", "9–10"), RM("Bāla Kāṇḍa", "70")]),
      rel("son", "aja", "verified", [BP("9", "10"), VP("4", "4")]),
    ],
    scriptureSources: [BP("9", "10"), VP("4", "4")],
  }),
  p({
    id: "aja",
    name: "Aja",
    englishName: "Aja",
    sanskritName: "अज",
    gender: "male",
    category: "king",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Son of Raghu; father of Daśaratha",
    description: "Aja, son of Raghu, is father of Daśaratha in the Solar/Raghu genealogy.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 3,
    relationships: [
      rel("father", "raghu", "verified", [BP("9", "10"), VP("4", "4")]),
      rel("son", "dasharatha", "verified", [BP("9", "10"), RM("Bāla Kāṇḍa", "70")]),
    ],
    scriptureSources: [BP("9", "10")],
  }),
  p({
    id: "dasharatha",
    name: "Daśaratha",
    englishName: "Dasharatha",
    sanskritName: "दशरथ",
    aliases: ["Dasaratha"],
    gender: "male",
    category: "king",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "King of Ayodhyā; father of Rāma",
    description:
      "Daśaratha, son of Aja, rules Ayodhyā. By Kausalyā, Kaikeyī and Sumitrā he fathers Rāma, Bharata, Lakṣmaṇa and Śatrughna.",
    primaryScripture: "Rāmāyaṇa",
    importance: 5,
    relationships: [
      rel("father", "aja", "verified", [BP("9", "10"), RM("Bāla Kāṇḍa", "70")]),
      rel("spouse", "kausalya", "verified", [RM("Bāla Kāṇḍa", "16–18")]),
      rel("spouse", "kaikeyi", "verified", [RM("Bāla Kāṇḍa", "16–18")]),
      rel("spouse", "sumitra", "verified", [RM("Bāla Kāṇḍa", "16–18")]),
      rel("son", "rama", "verified", [RM("Bāla Kāṇḍa", "18"), BP("9", "10")]),
      rel("son", "bharata", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("son", "lakshmana", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("son", "shatrughna", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("guru", "vasishtha", "traditional", [RM("Bāla Kāṇḍa")], "Vasiṣṭha is kulaguru of the Ayodhyā line."),
    ],
    scriptureSources: [RM("Bāla Kāṇḍa"), BP("9", "10")],
  }),
  p({
    id: "kausalya",
    name: "Kausalyā",
    englishName: "Kausalya",
    sanskritName: "कौसल्या",
    aliases: ["Kausalya"],
    gender: "female",
    category: "queen",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Chief queen of Daśaratha; mother of Rāma",
    description: "Kausalyā is the senior queen of Daśaratha and mother of Rāma.",
    primaryScripture: "Rāmāyaṇa",
    importance: 4,
    relationships: [
      rel("spouse", "dasharatha", "verified", [RM("Bāla Kāṇḍa", "16–18")]),
      rel("son", "rama", "verified", [RM("Bāla Kāṇḍa", "18")]),
    ],
    scriptureSources: [RM("Bāla Kāṇḍa", "18")],
  }),
  p({
    id: "kaikeyi",
    name: "Kaikeyī",
    englishName: "Kaikeyi",
    sanskritName: "कैकेयी",
    gender: "female",
    category: "queen",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Queen of Daśaratha; mother of Bharata",
    description: "Kaikeyī, daughter of the Kekaya king, is mother of Bharata and the queen whose boons send Rāma into exile.",
    primaryScripture: "Rāmāyaṇa",
    importance: 4,
    relationships: [
      rel("spouse", "dasharatha", "verified", [RM("Bāla Kāṇḍa", "16–18")]),
      rel("son", "bharata", "verified", [RM("Bāla Kāṇḍa", "18")]),
    ],
    scriptureSources: [RM("Bāla Kāṇḍa", "18"), RM("Ayodhyā Kāṇḍa")],
  }),
  p({
    id: "sumitra",
    name: "Sumitrā",
    englishName: "Sumitra",
    sanskritName: "सुमित्रा",
    gender: "female",
    category: "queen",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Queen of Daśaratha; mother of Lakṣmaṇa and Śatrughna",
    description: "Sumitrā is mother of the twins Lakṣmaṇa and Śatrughna.",
    primaryScripture: "Rāmāyaṇa",
    importance: 3,
    relationships: [
      rel("spouse", "dasharatha", "verified", [RM("Bāla Kāṇḍa", "16–18")]),
      rel("son", "lakshmana", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("son", "shatrughna", "verified", [RM("Bāla Kāṇḍa", "18")]),
    ],
    scriptureSources: [RM("Bāla Kāṇḍa", "18")],
  }),
];

/** Rāma's family */
export const RAMA_FAMILY: PersonDraft[] = [
  p({
    id: "rama",
    name: "Rāma",
    englishName: "Rama",
    sanskritName: "राम",
    aliases: ["Ram", "Raghunatha", "Raghunātha", "Sita-pati", "Maryada Purushottama"],
    gender: "male",
    category: "avatar",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Prince of Ayodhyā; avatāra of Viṣṇu",
    description:
      "Rāma, son of Daśaratha and Kausalyā, is the hero of the Rāmāyaṇa — exile, the recovery of Sītā, and the establishment of rāma-rājya.",
    primaryScripture: "Rāmāyaṇa",
    importance: 5,
    imagePlaceholder: "🏹",
    relationships: [
      rel("father", "dasharatha", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("mother", "kausalya", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("brother", "bharata", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("brother", "lakshmana", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("brother", "shatrughna", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("spouse", "sita", "verified", [RM("Bāla Kāṇḍa", "73"), RM("Araṇya Kāṇḍa")]),
      rel("son", "lava", "verified", [RM("Uttara Kāṇḍa")]),
      rel("son", "kusha", "verified", [RM("Uttara Kāṇḍa")]),
      rel("incarnation-of", "vishnu", "verified", [RM("Bāla Kāṇḍa", "15–17"), BP("9", "10")]),
      rel("guru", "vasishtha", "traditional", [RM("Bāla Kāṇḍa")]),
    ],
    scriptureSources: [RM("Bāla Kāṇḍa"), BP("9", "10–11")],
  }),
  p({
    id: "sita",
    name: "Sītā",
    englishName: "Sita",
    sanskritName: "सीता",
    aliases: ["Janaki", "Jānakī", "Maithili", "Vaidehi"],
    gender: "female",
    category: "queen",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Daughter of Janaka; wife of Rāma",
    description: "Sītā, found by King Janaka, marries Rāma, shares his exile, and is abducted by Rāvaṇa — the moral centre of the Rāmāyaṇa.",
    primaryScripture: "Rāmāyaṇa",
    importance: 5,
    relationships: [
      rel("adoptive-father", "janaka", "verified", [RM("Bāla Kāṇḍa", "66")]),
      rel("spouse", "rama", "verified", [RM("Bāla Kāṇḍa", "73")]),
      rel("son", "lava", "verified", [RM("Uttara Kāṇḍa")]),
      rel("son", "kusha", "verified", [RM("Uttara Kāṇḍa")]),
    ],
    scriptureSources: [RM("Bāla Kāṇḍa"), RM("Uttara Kāṇḍa")],
  }),
  p({
    id: "janaka",
    name: "Janaka",
    englishName: "Janaka",
    sanskritName: "जनक",
    aliases: ["Siradhvaja", "Sīradhvaja"],
    gender: "male",
    category: "king",
    era: "treta-yuga",
    dynasty: "videha",
    epithet: "King of Videha; adoptive father of Sītā",
    description: "Janaka of Mithilā finds Sītā in the furrow and raises her; Rāma wins her hand by stringing Śiva's bow.",
    primaryScripture: "Rāmāyaṇa",
    importance: 4,
    relationships: [
      rel("adoptive-daughter", "sita", "verified", [RM("Bāla Kāṇḍa", "66")]),
    ],
    scriptureSources: [RM("Bāla Kāṇḍa", "66–73")],
  }),
  p({
    id: "bharata",
    name: "Bharata",
    englishName: "Bharata",
    sanskritName: "भरत",
    gender: "male",
    category: "prince",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Son of Kaikeyī; regent of Ayodhyā",
    description: "Bharata, son of Daśaratha and Kaikeyī, refuses the throne won by intrigue and rules as Rāma's deputy from Nandigrāma.",
    primaryScripture: "Rāmāyaṇa",
    importance: 4,
    relationships: [
      rel("father", "dasharatha", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("mother", "kaikeyi", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("brother", "rama", "verified", [RM("Bāla Kāṇḍa", "18")]),
    ],
    scriptureSources: [RM("Ayodhyā Kāṇḍa")],
  }),
  p({
    id: "lakshmana",
    name: "Lakṣmaṇa",
    englishName: "Lakshmana",
    sanskritName: "लक्ष्मण",
    aliases: ["Laxman", "Lakshman"],
    gender: "male",
    category: "prince",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Constant companion of Rāma",
    description: "Lakṣmaṇa, son of Sumitrā, accompanies Rāma and Sītā into exile and slays Indrajit.",
    primaryScripture: "Rāmāyaṇa",
    importance: 5,
    relationships: [
      rel("father", "dasharatha", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("mother", "sumitra", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("brother", "rama", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("brother", "shatrughna", "verified", [RM("Bāla Kāṇḍa", "18")]),
    ],
    scriptureSources: [RM("Bāla Kāṇḍa", "18"), RM("Yuddha Kāṇḍa")],
  }),
  p({
    id: "shatrughna",
    name: "Śatrughna",
    englishName: "Shatrughna",
    sanskritName: "शत्रुघ्न",
    aliases: ["Satrughna"],
    gender: "male",
    category: "prince",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Youngest brother of Rāma",
    description: "Śatrughna, twin of Lakṣmaṇa and son of Sumitrā, supports Bharata and later conquers Lavaṇa.",
    primaryScripture: "Rāmāyaṇa",
    importance: 3,
    relationships: [
      rel("father", "dasharatha", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("mother", "sumitra", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("brother", "rama", "verified", [RM("Bāla Kāṇḍa", "18")]),
      rel("brother", "lakshmana", "verified", [RM("Bāla Kāṇḍa", "18")]),
    ],
    scriptureSources: [RM("Bāla Kāṇḍa", "18"), RM("Uttara Kāṇḍa")],
  }),
  p({
    id: "lava",
    name: "Lava",
    englishName: "Lava",
    sanskritName: "लव",
    gender: "male",
    category: "prince",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Son of Rāma and Sītā",
    description: "Lava, son of Rāma and Sītā, is raised in Vālmīki's āśrama and appears in the Uttara Kāṇḍa.",
    primaryScripture: "Rāmāyaṇa",
    importance: 3,
    relationships: [
      rel("father", "rama", "verified", [RM("Uttara Kāṇḍa")]),
      rel("mother", "sita", "verified", [RM("Uttara Kāṇḍa")]),
      rel("brother", "kusha", "verified", [RM("Uttara Kāṇḍa")]),
    ],
    scriptureSources: [RM("Uttara Kāṇḍa")],
  }),
  p({
    id: "kusha",
    name: "Kuśa",
    englishName: "Kusha",
    sanskritName: "कुश",
    aliases: ["Kusa"],
    gender: "male",
    category: "prince",
    era: "treta-yuga",
    dynasty: "raghu",
    epithet: "Son of Rāma and Sītā",
    description: "Kuśa, twin of Lava, continues the Raghu line in later tradition after the Aśvamedha episode.",
    primaryScripture: "Rāmāyaṇa",
    importance: 3,
    relationships: [
      rel("father", "rama", "verified", [RM("Uttara Kāṇḍa")]),
      rel("mother", "sita", "verified", [RM("Uttara Kāṇḍa")]),
      rel("brother", "lava", "verified", [RM("Uttara Kāṇḍa")]),
    ],
    scriptureSources: [RM("Uttara Kāṇḍa")],
  }),
];

/** Lunar Dynasty origin */
export const LUNAR: PersonDraft[] = [
  p({
    id: "chandra",
    name: "Candra",
    englishName: "Chandra",
    sanskritName: "चन्द्र",
    aliases: ["Soma", "Chandra", "Moon"],
    gender: "male",
    category: "deva",
    era: "creation",
    dynasty: "chandravamsa",
    epithet: "Moon; origin of the Lunar Dynasty",
    description: "Candra (Soma), son of Atri in the Purāṇic account, is the celestial source of the Candravaṃśa through Budha and Purūravas.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "atri", "verified", [BP("4", "1"), VP("4", "6")]),
      rel("son", "budha", "verified", [BP("9", "14"), VP("4", "6")]),
    ],
    scriptureSources: [BP("4", "1"), BP("9", "14"), VP("4", "6")],
  }),
  p({
    id: "budha",
    name: "Budha",
    englishName: "Budha",
    sanskritName: "बुध",
    gender: "male",
    category: "deva",
    era: "creation",
    dynasty: "chandravamsa",
    epithet: "Son of Candra; father of Purūravas",
    description: "Budha, son of Candra (and Tārā in the Purāṇic tale), fathers Purūravas by Ilā — founding the Lunar royal line.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    relationships: [
      rel("father", "chandra", "verified", [BP("9", "14"), VP("4", "6")]),
      rel("son", "pururavas", "verified", [BP("9", "14–15"), VP("4", "6–7")]),
    ],
    scriptureSources: [BP("9", "14"), VP("4", "6")],
  }),
  p({
    id: "pururavas",
    name: "Purūravas",
    englishName: "Pururavas",
    sanskritName: "पुरूरवस्",
    gender: "male",
    category: "dynasty-founder",
    era: "satya-yuga",
    dynasty: "chandravamsa",
    epithet: "First king of the Lunar Dynasty",
    description: "Purūravas, son of Budha and Ilā, is the founding king of the Candravaṃśa; his romance with Urvaśī is classical.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "budha", "verified", [BP("9", "14–15")]),
      rel("descendant", "yayati", "traditional", [BP("9", "18–19")], "Many generations intervene to Yayāti."),
    ],
    scriptureSources: [BP("9", "14–15"), VP("4", "6–7")],
  }),
  p({
    id: "yayati",
    name: "Yayāti",
    englishName: "Yayati",
    sanskritName: "ययाति",
    gender: "male",
    category: "king",
    era: "treta-yuga",
    dynasty: "chandravamsa",
    epithet: "Ancestor of Yadu and Puru lines",
    description:
      "Yayāti divides his kingdom among sons; Yadu and Puru become heads of the Yādava and Paurava branches of the Lunar Dynasty.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("ancestor", "pururavas", "traditional", [BP("9", "18")]),
      rel("son", "yadu", "verified", [BP("9", "18–23"), VP("4", "10"), MB("Ādi Parva", "75–85")]),
      rel("son", "puru", "verified", [BP("9", "18–22"), MB("Ādi Parva", "75–85")]),
    ],
    scriptureSources: [BP("9", "18–19"), MB("Ādi Parva", "75–85")],
  }),
  p({
    id: "yadu",
    name: "Yadu",
    englishName: "Yadu",
    sanskritName: "यदु",
    gender: "male",
    category: "dynasty-founder",
    era: "treta-yuga",
    dynasty: "yadu",
    epithet: "Eponym of the Yādavas",
    description: "Yadu, son of Yayāti, founds the Yadu line from which Vṛṣṇi, Vāsudeva and Kṛṣṇa descend.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "yayati", "verified", [BP("9", "18"), MB("Ādi Parva", "75")]),
      rel("descendant", "vasudeva", "traditional", [BP("9", "23–24"), HV()], "Many generations to Śūrasena/Vāsudeva."),
    ],
    scriptureSources: [BP("9", "18–24")],
  }),
  p({
    id: "puru",
    name: "Puru",
    englishName: "Puru",
    sanskritName: "पुरु",
    gender: "male",
    category: "dynasty-founder",
    era: "treta-yuga",
    dynasty: "paurava",
    epithet: "Ancestor of the Kurus and Pāṇḍavas",
    description: "Puru, son of Yayāti, receives the kingdom; through him descend Duṣyanta, Bharata, Kuru and the Pāṇḍava–Kaurava houses.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "yayati", "verified", [BP("9", "18–22"), MB("Ādi Parva", "75")]),
      rel("descendant", "kuru", "traditional", [BP("9", "22"), MB("Ādi Parva")], "Many generations intervene."),
    ],
    scriptureSources: [BP("9", "20–22")],
  }),
];

/** Yadu / Kṛṣṇa family */
export const YADU_KRISHNA: PersonDraft[] = [
  p({
    id: "vasudeva",
    name: "Vasudeva",
    englishName: "Vasudeva",
    sanskritName: "वसुदेव",
    aliases: ["Anakadundubhi", "Ānakadundubhi"],
    gender: "male",
    category: "king",
    era: "dvapara-yuga",
    dynasty: "yadu",
    epithet: "Father of Kṛṣṇa and Balarāma",
    description: "Vasudeva of the Yadu/Vṛṣṇi line marries Devakī; their son is Kṛṣṇa. With Rohiṇī he fathers Balarāma (transferred embryo in the Bhāgavata).",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("ancestor", "yadu", "traditional", [BP("9", "23–24"), HV()]),
      rel("spouse", "devaki", "verified", [BP("10", "1–3"), HV()]),
      rel("spouse", "rohini", "verified", [BP("10", "1–2")]),
      rel("son", "krishna", "verified", [BP("10", "3"), MB("Ādi Parva")]),
      rel("son", "balarama", "verified", [BP("10", "1–2")]),
    ],
    scriptureSources: [BP("10", "1–3"), HV()],
  }),
  p({
    id: "devaki",
    name: "Devakī",
    englishName: "Devaki",
    sanskritName: "देवकी",
    gender: "female",
    category: "queen",
    era: "dvapara-yuga",
    dynasty: "yadu",
    epithet: "Mother of Kṛṣṇa",
    description: "Devakī, sister of Kaṃsa, is mother of Kṛṣṇa; Kaṃsa imprisons her after a prophecy.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("spouse", "vasudeva", "verified", [BP("10", "1")]),
      rel("son", "krishna", "verified", [BP("10", "3")]),
      rel("brother", "kamsa", "verified", [BP("10", "1")]),
    ],
    scriptureSources: [BP("10", "1–3")],
  }),
  p({
    id: "rohini",
    name: "Rohiṇī",
    englishName: "Rohini",
    sanskritName: "रोहिणी",
    gender: "female",
    category: "queen",
    era: "dvapara-yuga",
    dynasty: "yadu",
    epithet: "Wife of Vasudeva; mother of Balarāma",
    description: "Rohiṇī receives the transferred embryo and gives birth to Balarāma in the Bhāgavata account.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    relationships: [
      rel("spouse", "vasudeva", "verified", [BP("10", "1–2")]),
      rel("son", "balarama", "verified", [BP("10", "1–2")]),
    ],
    scriptureSources: [BP("10", "1–2")],
  }),
  p({
    id: "kamsa",
    name: "Kaṃsa",
    englishName: "Kamsa",
    sanskritName: "कंस",
    aliases: ["Kansa"],
    gender: "male",
    category: "king",
    era: "dvapara-yuga",
    dynasty: "yadu",
    epithet: "Tyrant of Mathurā; maternal uncle of Kṛṣṇa",
    description: "Kaṃsa, brother of Devakī, usurps Mathurā and seeks to kill Devakī's children; slain by Kṛṣṇa.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    relationships: [
      rel("sister", "devaki", "verified", [BP("10", "1")]),
    ],
    scriptureSources: [BP("10", "1–44")],
  }),
  p({
    id: "krishna",
    name: "Kṛṣṇa",
    englishName: "Krishna",
    sanskritName: "कृष्ण",
    aliases: [
      "Krishna",
      "Krsna",
      "Govinda",
      "Madhava",
      "Mādhava",
      "Vasudeva",
      "Vāsudeva",
      "Hari",
      "Mukunda",
      "Yadava",
      "Yādava",
    ],
    gender: "male",
    category: "avatar",
    era: "dvapara-yuga",
    dynasty: "yadu",
    epithet: "Avatāra of Viṣṇu; speaker of the Bhagavad Gītā",
    description:
      "Kṛṣṇa, son of Vasudeva and Devakī, raised by Nanda and Yaśodā, is the central figure of the Bhāgavata's tenth skandha and the charioteer-teacher of the Gītā.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    imagePlaceholder: "🪈",
    relationships: [
      rel("father", "vasudeva", "verified", [BP("10", "3")]),
      rel("mother", "devaki", "verified", [BP("10", "3")]),
      rel("adoptive-father", "nanda", "verified", [BP("10", "5")]),
      rel("adoptive-mother", "yashoda", "verified", [BP("10", "5")]),
      rel("brother", "balarama", "verified", [BP("10", "1–2"), HV()]),
      rel("spouse", "rukmini", "verified", [BP("10", "52–54")]),
      rel("incarnation-of", "vishnu", "verified", [BP("10", "1–3"), BG("4")]),
    ],
    scriptureSources: [BP("10"), HV(), { work: "Bhagavad Gītā" }],
    relatedVerses: [
      { workCode: "bg", publicId: "bg.4.7", label: "I descend age after age" },
      { workCode: "bg", publicId: "bg.10.20", label: "I am the Self in all beings" },
    ],
  }),
  p({
    id: "balarama",
    name: "Balarāma",
    englishName: "Balarama",
    sanskritName: "बलराम",
    aliases: ["Baladeva", "Sankarsana", "Saṅkarṣaṇa", "Rama"],
    gender: "male",
    category: "avatar",
    era: "dvapara-yuga",
    dynasty: "yadu",
    epithet: "Elder brother of Kṛṣṇa",
    description: "Balarāma, son of Vasudeva (born of Rohiṇī), is Kṛṣṇa's elder brother and companion in Vraja and Dvārakā.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "vasudeva", "verified", [BP("10", "1–2")]),
      rel("mother", "rohini", "verified", [BP("10", "1–2")]),
      rel("brother", "krishna", "verified", [BP("10", "1–8")]),
    ],
    scriptureSources: [BP("10", "1–8"), HV()],
  }),
  p({
    id: "nanda",
    name: "Nanda",
    englishName: "Nanda",
    sanskritName: "नन्द",
    aliases: ["Nanda Baba", "Nandaraja"],
    gender: "male",
    category: "other",
    era: "dvapara-yuga",
    dynasty: "yadu",
    epithet: "Foster-father of Kṛṣṇa in Vraja",
    description: "Nanda, chief of the cowherds of Vraja, raises Kṛṣṇa with Yaśodā after Vasudeva brings the infant to Gokula.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    relationships: [
      rel("spouse", "yashoda", "verified", [BP("10", "5")]),
      rel("adoptive-son", "krishna", "verified", [BP("10", "5")]),
    ],
    scriptureSources: [BP("10", "5–8")],
  }),
  p({
    id: "yashoda",
    name: "Yaśodā",
    englishName: "Yashoda",
    sanskritName: "यशोदा",
    aliases: ["Yashoda", "Yasoda"],
    gender: "female",
    category: "other",
    era: "dvapara-yuga",
    dynasty: "yadu",
    epithet: "Foster-mother of Kṛṣṇa",
    description: "Yaśodā raises Kṛṣṇa in Gokula; the Bhāgavata recounts her maternal love and the vision of the universal form in his mouth.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("spouse", "nanda", "verified", [BP("10", "5")]),
      rel("adoptive-son", "krishna", "verified", [BP("10", "5–8")]),
    ],
    scriptureSources: [BP("10", "5–8")],
  }),
  p({
    id: "rukmini",
    name: "Rukmiṇī",
    englishName: "Rukmini",
    sanskritName: "रुक्मिणी",
    gender: "female",
    category: "queen",
    era: "dvapara-yuga",
    dynasty: "yadu",
    epithet: "Chief consort of Kṛṣṇa at Dvārakā",
    description: "Rukmiṇī, princess of Vidarbha, is taken by Kṛṣṇa from an unwanted marriage; she is foremost among his queens in the Bhāgavata.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    relationships: [rel("spouse", "krishna", "verified", [BP("10", "52–54")])],
    scriptureSources: [BP("10", "52–54")],
  }),
];

/** Kuru house through Pāṇḍavas / Kauravas */
export const KURU_LINE: PersonDraft[] = [
  p({
    id: "kuru",
    name: "Kuru",
    englishName: "Kuru",
    sanskritName: "कुरु",
    gender: "male",
    category: "dynasty-founder",
    era: "treta-yuga",
    dynasty: "kuru",
    epithet: "Eponym of the Kuru dynasty",
    description: "Kuru gives his name to Kurukṣetra and the Kuru line; Bhīṣma, Dhṛtarāṣṭra and Pāṇḍu descend in this house.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("ancestor", "puru", "traditional", [BP("9", "22"), MB("Ādi Parva")]),
      rel("descendant", "shantanu", "traditional", [MB("Ādi Parva", "94–100")], "Generations intervene."),
    ],
    scriptureSources: [MB("Ādi Parva"), BP("9", "22")],
  }),
  p({
    id: "shantanu",
    name: "Śaṃtanu",
    englishName: "Shantanu",
    sanskritName: "शंतनु",
    aliases: ["Santanu", "Shantanu"],
    gender: "male",
    category: "king",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "King of Hastināpura; father of Bhīṣma",
    description: "Śaṃtanu marries Gaṅgā and later Satyavatī; by Gaṅgā he fathers Devavrata (Bhīṣma).",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("ancestor", "kuru", "traditional", [MB("Ādi Parva", "94")]),
      rel("spouse", "ganga", "verified", [MB("Ādi Parva", "96–100")]),
      rel("spouse", "satyavati", "verified", [MB("Ādi Parva", "100")]),
      rel("son", "bhishma", "verified", [MB("Ādi Parva", "96–100")]),
      rel("son", "vichitravirya", "verified", [MB("Ādi Parva", "100–101")]),
    ],
    scriptureSources: [MB("Ādi Parva", "94–101")],
  }),
  p({
    id: "ganga",
    name: "Gaṅgā",
    englishName: "Ganga",
    sanskritName: "गङ्गा",
    aliases: ["Ganga", "Jahnavi", "Jāhnavī"],
    gender: "female",
    category: "devi",
    era: "eternal",
    dynasty: "kuru",
    epithet: "River goddess; mother of Bhīṣma",
    description: "Gaṅgā marries Śaṃtanu and bears Devavrata (Bhīṣma), later returning to her celestial form.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("spouse", "shantanu", "verified", [MB("Ādi Parva", "96–100")]),
      rel("son", "bhishma", "verified", [MB("Ādi Parva", "96–100")]),
    ],
    scriptureSources: [MB("Ādi Parva", "96–100")],
  }),
  p({
    id: "satyavati",
    name: "Satyavatī",
    englishName: "Satyavati",
    sanskritName: "सत्यवती",
    aliases: ["Matsyagandha"],
    gender: "female",
    category: "queen",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Queen of Śaṃtanu; mother of Vyāsa and Vicitravīrya",
    description:
      "Satyavatī marries Śaṃtanu on condition that her sons inherit. Before marriage she bore Kṛṣṇa-Dvaipāyana Vyāsa to Parāśara.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("spouse", "shantanu", "verified", [MB("Ādi Parva", "100")]),
      rel("son", "vichitravirya", "verified", [MB("Ādi Parva", "100–101")]),
      rel("son", "vyasa", "verified", [MB("Ādi Parva", "57–63")], "Born of Parāśara before her marriage to Śaṃtanu."),
    ],
    scriptureSources: [MB("Ādi Parva", "57–101")],
  }),
  p({
    id: "bhishma",
    name: "Bhīṣma",
    englishName: "Bhishma",
    sanskritName: "भीष्म",
    aliases: ["Devavrata", "Bhishma Pitamaha", "Gangeya"],
    gender: "male",
    category: "warrior",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Son of Gaṅgā; vow of celibacy",
    description:
      "Bhīṣma (Devavrata), son of Śaṃtanu and Gaṅgā, takes the terrible vow of celibacy so that Satyavatī's line may inherit; he is grandsire of the war.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("father", "shantanu", "verified", [MB("Ādi Parva", "96–100")]),
      rel("mother", "ganga", "verified", [MB("Ādi Parva", "96–100")]),
      rel("brother", "vichitravirya", "verified", [MB("Ādi Parva", "100")], "Half-brother."),
    ],
    scriptureSources: [MB("Ādi Parva", "96–100"), MB("Bhīṣma Parva")],
    relatedVerses: [{ workCode: "bg", publicId: "bg.1.8", label: "Named among warriors" }],
  }),
  p({
    id: "vyasa",
    name: "Vyāsa",
    englishName: "Vyasa",
    sanskritName: "व्यास",
    aliases: ["Veda Vyasa", "Krishna Dvaipayana", "Kṛṣṇa-Dvaipāyana", "Dvaipayana"],
    gender: "male",
    category: "rishi",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Compiler of the Vedas; author of the Mahābhārata",
    description:
      "Kṛṣṇa-Dvaipāyana Vyāsa, son of Parāśara and Satyavatī, sires Dhṛtarāṣṭra, Pāṇḍu and Vidura by niyoga for Vicitravīrya's widows.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("mother", "satyavati", "verified", [MB("Ādi Parva", "57–63")]),
      rel("son", "dhritarashtra", "verified", [MB("Ādi Parva", "105–106")]),
      rel("son", "pandu", "verified", [MB("Ādi Parva", "105–106")]),
      rel("son", "vidura", "verified", [MB("Ādi Parva", "105–106")]),
    ],
    scriptureSources: [MB("Ādi Parva", "57–106")],
  }),
  p({
    id: "vichitravirya",
    name: "Vicitravīrya",
    englishName: "Vichitravirya",
    sanskritName: "विचित्रवीर्य",
    gender: "male",
    category: "king",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Son of Śaṃtanu and Satyavatī",
    description: "Vicitravīrya marries Ambikā and Ambālikā but dies childless; Vyāsa raises heirs by niyoga.",
    primaryScripture: "Mahābhārata",
    importance: 3,
    relationships: [
      rel("father", "shantanu", "verified", [MB("Ādi Parva", "100")]),
      rel("mother", "satyavati", "verified", [MB("Ādi Parva", "100")]),
      rel("spouse", "ambika", "verified", [MB("Ādi Parva", "102–105")]),
      rel("spouse", "ambalika", "verified", [MB("Ādi Parva", "102–105")]),
    ],
    scriptureSources: [MB("Ādi Parva", "100–105")],
  }),
  p({
    id: "ambika",
    name: "Ambikā",
    englishName: "Ambika",
    sanskritName: "अम्बिका",
    gender: "female",
    category: "queen",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Mother of Dhṛtarāṣṭra (by niyoga)",
    description: "Ambikā, widow of Vicitravīrya, bears Dhṛtarāṣṭra through Vyāsa's niyoga.",
    primaryScripture: "Mahābhārata",
    importance: 3,
    relationships: [
      rel("spouse", "vichitravirya", "verified", [MB("Ādi Parva", "102")]),
      rel("son", "dhritarashtra", "verified", [MB("Ādi Parva", "105–106")]),
    ],
    scriptureSources: [MB("Ādi Parva", "105–106")],
  }),
  p({
    id: "ambalika",
    name: "Ambālikā",
    englishName: "Ambalika",
    sanskritName: "अम्बालिका",
    gender: "female",
    category: "queen",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Mother of Pāṇḍu (by niyoga)",
    description: "Ambālikā, widow of Vicitravīrya, bears Pāṇḍu through Vyāsa's niyoga.",
    primaryScripture: "Mahābhārata",
    importance: 3,
    relationships: [
      rel("spouse", "vichitravirya", "verified", [MB("Ādi Parva", "102")]),
      rel("son", "pandu", "verified", [MB("Ādi Parva", "105–106")]),
    ],
    scriptureSources: [MB("Ādi Parva", "105–106")],
  }),
  p({
    id: "dhritarashtra",
    name: "Dhṛtarāṣṭra",
    englishName: "Dhritarashtra",
    sanskritName: "धृतराष्ट्र",
    aliases: ["Dhritrashtra"],
    gender: "male",
    category: "king",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Blind king; father of the Kauravas",
    description: "Dhṛtarāṣṭra, son of Vyāsa and Ambikā, fathers one hundred sons by Gāndhārī, led by Duryodhana.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("father", "vyasa", "verified", [MB("Ādi Parva", "105–106")]),
      rel("mother", "ambika", "verified", [MB("Ādi Parva", "105–106")]),
      rel("brother", "pandu", "verified", [MB("Ādi Parva", "105–106")]),
      rel("brother", "vidura", "verified", [MB("Ādi Parva", "105–106")]),
      rel("spouse", "gandhari", "verified", [MB("Ādi Parva", "109–110")]),
      rel("son", "duryodhana", "verified", [MB("Ādi Parva", "114–115")]),
      rel("son", "dushasana", "verified", [MB("Ādi Parva", "114–115")]),
    ],
    scriptureSources: [MB("Ādi Parva", "105–115")],
  }),
  p({
    id: "gandhari",
    name: "Gāndhārī",
    englishName: "Gandhari",
    sanskritName: "गान्धारी",
    gender: "female",
    category: "queen",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Wife of Dhṛtarāṣṭra; mother of the Kauravas",
    description: "Gāndhārī, princess of Gandhāra, blindfolds herself and bears the hundred Kaurava sons.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("spouse", "dhritarashtra", "verified", [MB("Ādi Parva", "109–110")]),
      rel("son", "duryodhana", "verified", [MB("Ādi Parva", "114–115")]),
      rel("son", "dushasana", "verified", [MB("Ādi Parva", "114–115")]),
      rel("daughter", "duhsala", "verified", [MB("Ādi Parva", "115")]),
    ],
    scriptureSources: [MB("Ādi Parva", "109–115")],
  }),
  p({
    id: "pandu",
    name: "Pāṇḍu",
    englishName: "Pandu",
    sanskritName: "पाण्डु",
    gender: "male",
    category: "king",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Father of the Pāṇḍavas (by divine niyoga)",
    description:
      "Pāṇḍu, son of Vyāsa and Ambālikā, cannot father children by curse; his wives Kuntī and Mādrī invoke gods to bear the five Pāṇḍavas.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("father", "vyasa", "verified", [MB("Ādi Parva", "105–106")]),
      rel("mother", "ambalika", "verified", [MB("Ādi Parva", "105–106")]),
      rel("brother", "dhritarashtra", "verified", [MB("Ādi Parva", "105")]),
      rel("spouse", "kunti", "verified", [MB("Ādi Parva", "111–114")]),
      rel("spouse", "madri", "verified", [MB("Ādi Parva", "111–114")]),
      rel("son", "yudhishthira", "verified", [MB("Ādi Parva", "123")], "Born of Dharma by Kuntī's mantra."),
      rel("son", "bhima", "verified", [MB("Ādi Parva", "123")], "Born of Vāyu."),
      rel("son", "arjuna", "verified", [MB("Ādi Parva", "123")], "Born of Indra."),
      rel("son", "nakula", "verified", [MB("Ādi Parva", "124")], "Born of the Aśvins by Mādrī."),
      rel("son", "sahadeva", "verified", [MB("Ādi Parva", "124")]),
    ],
    scriptureSources: [MB("Ādi Parva", "105–124")],
  }),
  p({
    id: "vidura",
    name: "Vidura",
    englishName: "Vidura",
    sanskritName: "विदुर",
    gender: "male",
    category: "other",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Wise counsellor; brother of Dhṛtarāṣṭra and Pāṇḍu",
    description: "Vidura, son of Vyāsa and a palace maid, is famed for dharma-counsel in the Mahābhārata.",
    primaryScripture: "Mahābhārata",
    importance: 4,
    relationships: [
      rel("father", "vyasa", "verified", [MB("Ādi Parva", "105–106")]),
      rel("brother", "dhritarashtra", "verified", [MB("Ādi Parva", "105")]),
      rel("brother", "pandu", "verified", [MB("Ādi Parva", "105")]),
    ],
    scriptureSources: [MB("Ādi Parva", "105–106")],
  }),
  p({
    id: "kunti",
    name: "Kuntī",
    englishName: "Kunti",
    sanskritName: "कुन्ती",
    aliases: ["Pritha", "Pṛthā"],
    gender: "female",
    category: "queen",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Mother of Yudhiṣṭhira, Bhīma, Arjuna and Karṇa",
    description:
      "Kuntī (Pṛthā), wife of Pāṇḍu, bears three Pāṇḍavas by divine fathers and earlier bore Karṇa by Sūrya.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("spouse", "pandu", "verified", [MB("Ādi Parva", "111")]),
      rel("son", "karna", "verified", [MB("Ādi Parva", "104–111")], "Born before marriage, of Sūrya."),
      rel("son", "yudhishthira", "verified", [MB("Ādi Parva", "123")]),
      rel("son", "bhima", "verified", [MB("Ādi Parva", "123")]),
      rel("son", "arjuna", "verified", [MB("Ādi Parva", "123")]),
    ],
    scriptureSources: [MB("Ādi Parva", "104–124")],
  }),
  p({
    id: "madri",
    name: "Mādrī",
    englishName: "Madri",
    sanskritName: "माद्री",
    gender: "female",
    category: "queen",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Mother of Nakula and Sahadeva",
    description: "Mādrī, second wife of Pāṇḍu, bears the twins Nakula and Sahadeva by the Aśvins.",
    primaryScripture: "Mahābhārata",
    importance: 4,
    relationships: [
      rel("spouse", "pandu", "verified", [MB("Ādi Parva", "111")]),
      rel("son", "nakula", "verified", [MB("Ādi Parva", "124")]),
      rel("son", "sahadeva", "verified", [MB("Ādi Parva", "124")]),
    ],
    scriptureSources: [MB("Ādi Parva", "124")],
  }),
];

export const PANDAVAS: PersonDraft[] = [
  p({
    id: "yudhishthira",
    name: "Yudhiṣṭhira",
    englishName: "Yudhishthira",
    sanskritName: "युधिष्ठिर",
    aliases: ["Dharmaraja", "Dharmarāja", "Ajatashatru"],
    gender: "male",
    category: "king",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Eldest Pāṇḍava; son of Dharma",
    description: "Yudhiṣṭhira, born of Dharma through Kuntī, is the dharmic eldest of the five brothers and victor of the Kurukṣetra war.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("father", "pandu", "verified", [MB("Ādi Parva", "123")]),
      rel("mother", "kunti", "verified", [MB("Ādi Parva", "123")]),
      rel("brother", "bhima", "verified", [MB("Ādi Parva", "123")]),
      rel("brother", "arjuna", "verified", [MB("Ādi Parva", "123")]),
      rel("brother", "nakula", "verified", [MB("Ādi Parva", "124")]),
      rel("brother", "sahadeva", "verified", [MB("Ādi Parva", "124")]),
      rel("spouse", "draupadi", "verified", [MB("Ādi Parva", "174–199")]),
    ],
    scriptureSources: [MB("Ādi Parva", "123"), MB("Sabhā Parva")],
  }),
  p({
    id: "bhima",
    name: "Bhīma",
    englishName: "Bhima",
    sanskritName: "भीम",
    aliases: ["Bhimasena", "Vrikodara", "Vṛkodara"],
    gender: "male",
    category: "warrior",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Second Pāṇḍava; son of Vāyu",
    description: "Bhīma, son of Vāyu through Kuntī, is the strongest of the brothers and slayer of many Kauravas including Duryodhana.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("father", "pandu", "verified", [MB("Ādi Parva", "123")]),
      rel("mother", "kunti", "verified", [MB("Ādi Parva", "123")]),
      rel("brother", "yudhishthira", "verified", [MB("Ādi Parva", "123")]),
      rel("spouse", "draupadi", "verified", [MB("Ādi Parva", "199")]),
    ],
    scriptureSources: [MB("Ādi Parva", "123")],
  }),
  p({
    id: "arjuna",
    name: "Arjuna",
    englishName: "Arjuna",
    sanskritName: "अर्जुन",
    aliases: ["Partha", "Pārtha", "Dhananjaya", "Gudakesha", "Guḍākeśa", "Kiriti"],
    gender: "male",
    category: "warrior",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Third Pāṇḍava; hearer of the Bhagavad Gītā",
    description: "Arjuna, son of Indra through Kuntī, is the premier archer of the age and the interlocutor of the Bhagavad Gītā.",
    primaryScripture: "Bhagavad Gītā",
    importance: 5,
    relationships: [
      rel("father", "pandu", "verified", [MB("Ādi Parva", "123")]),
      rel("mother", "kunti", "verified", [MB("Ādi Parva", "123")]),
      rel("brother", "yudhishthira", "verified", [MB("Ādi Parva", "123")]),
      rel("spouse", "draupadi", "verified", [MB("Ādi Parva", "199")]),
      rel("spouse", "subhadra", "verified", [MB("Ādi Parva", "211–221")]),
      rel("son", "abhimanyu", "verified", [MB("Ādi Parva", "221")]),
    ],
    scriptureSources: [MB("Ādi Parva", "123"), BG("1")],
    relatedVerses: [{ workCode: "bg", publicId: "bg.2.3", label: "Do not yield to unmanliness" }],
  }),
  p({
    id: "nakula",
    name: "Nakula",
    englishName: "Nakula",
    sanskritName: "नकुल",
    gender: "male",
    category: "warrior",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Fourth Pāṇḍava; son of the Aśvins",
    description: "Nakula, twin of Sahadeva, is born of the Aśvins through Mādrī.",
    primaryScripture: "Mahābhārata",
    importance: 4,
    relationships: [
      rel("father", "pandu", "verified", [MB("Ādi Parva", "124")]),
      rel("mother", "madri", "verified", [MB("Ādi Parva", "124")]),
      rel("brother", "sahadeva", "verified", [MB("Ādi Parva", "124")]),
      rel("spouse", "draupadi", "verified", [MB("Ādi Parva", "199")]),
    ],
    scriptureSources: [MB("Ādi Parva", "124")],
  }),
  p({
    id: "sahadeva",
    name: "Sahadeva",
    englishName: "Sahadeva",
    sanskritName: "सहदेव",
    gender: "male",
    category: "warrior",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Youngest Pāṇḍava; son of the Aśvins",
    description: "Sahadeva, twin of Nakula, is born of the Aśvins through Mādrī and noted for wisdom.",
    primaryScripture: "Mahābhārata",
    importance: 4,
    relationships: [
      rel("father", "pandu", "verified", [MB("Ādi Parva", "124")]),
      rel("mother", "madri", "verified", [MB("Ādi Parva", "124")]),
      rel("brother", "nakula", "verified", [MB("Ādi Parva", "124")]),
      rel("spouse", "draupadi", "verified", [MB("Ādi Parva", "199")]),
    ],
    scriptureSources: [MB("Ādi Parva", "124")],
  }),
  p({
    id: "draupadi",
    name: "Draupadī",
    englishName: "Draupadi",
    sanskritName: "द्रौपदी",
    aliases: ["Panchali", "Pāñcālī", "Yajnaseni", "Yājñasenī", "Krishnaa"],
    gender: "female",
    category: "queen",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Wife of the five Pāṇḍavas",
    description: "Draupadī, daughter of Drupada, becomes the common wife of the five Pāṇḍavas after the svayaṃvara — a arrangement explained by prior boon and Vyāsa's counsel.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("spouse", "yudhishthira", "verified", [MB("Ādi Parva", "199")]),
      rel("spouse", "bhima", "verified", [MB("Ādi Parva", "199")]),
      rel("spouse", "arjuna", "verified", [MB("Ādi Parva", "199")]),
      rel("spouse", "nakula", "verified", [MB("Ādi Parva", "199")]),
      rel("spouse", "sahadeva", "verified", [MB("Ādi Parva", "199")]),
    ],
    scriptureSources: [MB("Ādi Parva", "174–199")],
  }),
  p({
    id: "subhadra",
    name: "Subhadrā",
    englishName: "Subhadra",
    sanskritName: "सुभद्रा",
    gender: "female",
    category: "princess",
    era: "dvapara-yuga",
    dynasty: "yadu",
    epithet: "Sister of Kṛṣṇa; wife of Arjuna; mother of Abhimanyu",
    description: "Subhadrā, sister of Kṛṣṇa and Balarāma, marries Arjuna and bears Abhimanyu.",
    primaryScripture: "Mahābhārata",
    importance: 4,
    relationships: [
      rel("brother", "krishna", "verified", [MB("Ādi Parva", "211–221"), BP("10")]),
      rel("brother", "balarama", "verified", [MB("Ādi Parva", "211")]),
      rel("spouse", "arjuna", "verified", [MB("Ādi Parva", "211–221")]),
      rel("son", "abhimanyu", "verified", [MB("Ādi Parva", "221")]),
    ],
    scriptureSources: [MB("Ādi Parva", "211–221")],
  }),
  p({
    id: "abhimanyu",
    name: "Abhimanyu",
    englishName: "Abhimanyu",
    sanskritName: "अभिमन्यु",
    gender: "male",
    category: "warrior",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Son of Arjuna and Subhadrā",
    description: "Abhimanyu, son of Arjuna and Subhadrā, dies heroically in the cakra-vyūha on the thirteenth day of battle.",
    primaryScripture: "Mahābhārata",
    importance: 4,
    relationships: [
      rel("father", "arjuna", "verified", [MB("Ādi Parva", "221")]),
      rel("mother", "subhadra", "verified", [MB("Ādi Parva", "221")]),
    ],
    scriptureSources: [MB("Ādi Parva", "221"), MB("Droṇa Parva")],
  }),
  p({
    id: "karna",
    name: "Karṇa",
    englishName: "Karna",
    sanskritName: "कर्ण",
    aliases: ["Radheya", "Vasushena", "Suryaputra"],
    gender: "male",
    category: "warrior",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Son of Kuntī and Sūrya; ally of Duryodhana",
    description:
      "Karṇa is born of Kuntī and Sūrya before her marriage, raised by Adhiratha and Rādhā, and fights for Duryodhana.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("mother", "kunti", "verified", [MB("Ādi Parva", "104–111")]),
      rel("brother", "yudhishthira", "verified", [MB("Ādi Parva"), MB("Karṇa Parva")], "Maternal half-brother of the Pāṇḍavas — revealed late."),
    ],
    scriptureSources: [MB("Ādi Parva", "104–111"), MB("Karṇa Parva")],
  }),
];

export const KAURAVAS: PersonDraft[] = [
  p({
    id: "duryodhana",
    name: "Duryodhana",
    englishName: "Duryodhana",
    sanskritName: "दुर्योधन",
    aliases: ["Suyodhana"],
    gender: "male",
    category: "prince",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Eldest Kaurava; rival of the Pāṇḍavas",
    description: "Duryodhana, eldest son of Dhṛtarāṣṭra and Gāndhārī, leads the Kaurava side in the Kurukṣetra war.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("father", "dhritarashtra", "verified", [MB("Ādi Parva", "114–115")]),
      rel("mother", "gandhari", "verified", [MB("Ādi Parva", "114–115")]),
      rel("brother", "dushasana", "verified", [MB("Ādi Parva", "114–115")]),
      rel("sister", "duhsala", "verified", [MB("Ādi Parva", "115")]),
    ],
    scriptureSources: [MB("Ādi Parva", "114–115"), MB("Śalya Parva")],
  }),
  p({
    id: "dushasana",
    name: "Duḥśāsana",
    englishName: "Dushasana",
    sanskritName: "दुःशासन",
    aliases: ["Duhshasana", "Dushasana"],
    gender: "male",
    category: "prince",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Brother of Duryodhana",
    description: "Duḥśāsana, second among the Kaurava brothers, is notorious for the disrobing of Draupadī and is slain by Bhīma.",
    primaryScripture: "Mahābhārata",
    importance: 4,
    relationships: [
      rel("father", "dhritarashtra", "verified", [MB("Ādi Parva", "114–115")]),
      rel("mother", "gandhari", "verified", [MB("Ādi Parva", "114–115")]),
      rel("brother", "duryodhana", "verified", [MB("Ādi Parva", "114–115")]),
    ],
    scriptureSources: [MB("Ādi Parva", "114–115"), MB("Sabhā Parva")],
  }),
  p({
    id: "duhsala",
    name: "Duḥśalā",
    englishName: "Duhsala",
    sanskritName: "दुःशला",
    aliases: ["Dushala", "Duhshala"],
    gender: "female",
    category: "princess",
    era: "dvapara-yuga",
    dynasty: "kuru",
    epithet: "Daughter of Dhṛtarāṣṭra and Gāndhārī",
    description: "Duḥśalā is the only daughter of Dhṛtarāṣṭra and Gāndhārī among the hundred-and-one siblings.",
    primaryScripture: "Mahābhārata",
    importance: 2,
    relationships: [
      rel("father", "dhritarashtra", "verified", [MB("Ādi Parva", "115")]),
      rel("mother", "gandhari", "verified", [MB("Ādi Parva", "115")]),
      rel("brother", "duryodhana", "verified", [MB("Ādi Parva", "115")]),
    ],
    scriptureSources: [MB("Ādi Parva", "115")],
  }),
];

/** Additional major ṛṣis / kings not covered above */
export const MAJOR_RISHIS: PersonDraft[] = [
  p({
    id: "valmiki",
    name: "Vālmīki",
    englishName: "Valmiki",
    sanskritName: "वाल्मीकि",
    gender: "male",
    category: "rishi",
    era: "treta-yuga",
    epithet: "Ādi kavi; author of the Rāmāyaṇa",
    description: "Vālmīki composes the Rāmāyaṇa and shelters Sītā; Lava and Kuśa learn the poem in his āśrama.",
    primaryScripture: "Rāmāyaṇa",
    importance: 5,
    relationships: [],
    scriptureSources: [RM("Bāla Kāṇḍa", "1–4"), RM("Uttara Kāṇḍa")],
    notes: "Traditional accounts of his earlier life vary; parentage is not asserted here without a single primary consensus.",
  }),
  p({
    id: "parasara",
    name: "Parāśara",
    englishName: "Parashara",
    sanskritName: "पराशर",
    gender: "male",
    category: "rishi",
    era: "dvapara-yuga",
    epithet: "Father of Vyāsa",
    description: "Parāśara fathers Kṛṣṇa-Dvaipāyana Vyāsa by Satyavatī (Matsyagandhā) as told in the Mahābhārata.",
    primaryScripture: "Mahābhārata",
    importance: 4,
    relationships: [
      rel("son", "vyasa", "verified", [MB("Ādi Parva", "57–63")]),
    ],
    scriptureSources: [MB("Ādi Parva", "57–63")],
  }),
];

export const MAJOR_KINGS: PersonDraft[] = [
  // Cross-cutting “major kings” module reuses dynasty figures — see rebuild modules.
];
