/**
 * Kaśyapa's wives and the separated Daitya / Dānava / Deva / Nāga lines.
 */
import { BP, VP, MB, BG, HV, RM, rel, type Rel } from "./cites.mts";
import { type PersonDraft } from "./people-cosmic.mts";

function p(draft: PersonDraft): PersonDraft {
  return {
    ...draft,
    iastName: draft.iastName ?? draft.name,
    aliases: draft.aliases ?? [],
    importance: draft.importance ?? 3,
    relationships: draft.relationships ?? [],
    scriptureSources: draft.scriptureSources ?? [],
  };
}

export const KASYAPA_LINE: PersonDraft[] = [
  p({
    id: "kashyapa",
    name: "Kaśyapa",
    englishName: "Kashyapa",
    sanskritName: "कश्यप",
    aliases: ["Kasyapa"],
    gender: "male",
    category: "prajapati",
    era: "creation",
    dynasty: "kashyapa",
    epithet: "Progenitor of Devas, Daityas, Dānavas, Nāgas and others",
    description:
      "Kaśyapa, son of Marīci, marries many daughters of Dakṣa. From Aditi come the Ādityas (Devas); from Diti the Daityas; from Danu the Dānavas; from Kadrū the Nāgas.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "marichi", "verified", [BP("3", "12"), VP("1", "7")]),
      rel("spouse", "aditi", "verified", [BP("6", "6"), VP("1", "15")]),
      rel("spouse", "diti", "verified", [BP("3", "14"), VP("1", "15")]),
      rel("spouse", "danu", "verified", [BP("6", "6"), VP("1", "15")]),
      rel("spouse", "kadru", "verified", [BP("6", "6"), MB("Ādi Parva", "16")]),
      rel("son", "indra", "verified", [BP("6", "18"), VP("1", "15")], "Indra is an Āditya, son of Kaśyapa and Aditi."),
      rel("son", "vivasvan", "verified", [BP("6", "6"), VP("1", "15"), BG("4")], "Vivasvān is an Āditya."),
      rel("son", "hiranyakashipu", "verified", [BP("7", "2"), BP("3", "14")]),
      rel("son", "hiranyaksha", "verified", [BP("3", "14–19")]),
      rel("daughter", "simhika", "verified", [BP("6", "18"), BP("8", "10")]),
      rel("son", "vipracitti", "verified", [BP("6", "6"), VP("1", "21")], "Dānava son of Danu."),
      rel("son", "ananta", "verified", [BP("5", "25"), BP("6", "6")]),
      rel("son", "vasuki", "verified", [BP("6", "6"), MB("Ādi Parva", "16–35")]),
      rel("son", "takshaka", "verified", [MB("Ādi Parva", "3"), BP("6", "6")]),
    ],
    scriptureSources: [BP("6", "6"), VP("1", "15"), MB("Ādi Parva", "16")],
  }),
  p({
    id: "aditi",
    name: "Aditi",
    englishName: "Aditi",
    sanskritName: "अदिति",
    gender: "female",
    category: "devi",
    era: "creation",
    dynasty: "aditya",
    epithet: "Mother of the Ādityas",
    description: "Aditi, daughter of Dakṣa and wife of Kaśyapa, is mother of the Ādityas — including Indra and Vivasvān.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "daksha", "verified", [BP("6", "6"), VP("1", "15")]),
      rel("spouse", "kashyapa", "verified", [BP("6", "6")]),
      rel("sister", "diti", "verified", [BP("6", "6")]),
      rel("sister", "danu", "verified", [BP("6", "6")]),
      rel("son", "indra", "verified", [BP("6", "18")]),
      rel("son", "vivasvan", "verified", [BP("6", "6"), BG("4")]),
      rel("son", "varuna", "traditional", [BP("6", "6"), VP("1", "15")], "Named among Ādityas in Purāṇic lists."),
      rel("son", "mitra", "traditional", [BP("6", "6"), VP("1", "15")]),
      rel("son", "aryaman", "traditional", [VP("1", "15")]),
      rel("son", "bhaga", "traditional", [VP("1", "15")]),
      rel("son", "pushan", "traditional", [VP("1", "15")]),
      rel("son", "savitr", "traditional", [VP("1", "15")]),
    ],
    scriptureSources: [BP("6", "6"), VP("1", "15")],
  }),
  p({
    id: "diti",
    name: "Diti",
    englishName: "Diti",
    sanskritName: "दिति",
    gender: "female",
    category: "daitya",
    era: "creation",
    dynasty: "daitya",
    epithet: "Mother of the Daityas",
    description:
      "Diti, daughter of Dakṣa and wife of Kaśyapa, is the mother of Hiraṇyakaśipu, Hiraṇyākṣa and Siṃhikā — the root of the Daitya line.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "daksha", "verified", [BP("3", "14"), VP("1", "15")]),
      rel("spouse", "kashyapa", "verified", [BP("3", "14")]),
      rel("sister", "aditi", "verified", [BP("6", "6")]),
      rel("sister", "danu", "verified", [BP("6", "6")]),
      rel("son", "hiranyakashipu", "verified", [BP("7", "2"), BP("3", "14")]),
      rel("son", "hiranyaksha", "verified", [BP("3", "14–19")]),
      rel("daughter", "simhika", "verified", [BP("6", "18")]),
    ],
    scriptureSources: [BP("3", "14"), BP("7", "2")],
  }),
  p({
    id: "danu",
    name: "Danu",
    englishName: "Danu",
    sanskritName: "दनु",
    gender: "female",
    category: "danava",
    era: "creation",
    dynasty: "danava",
    epithet: "Mother of the Dānavas",
    description: "Danu, daughter of Dakṣa and wife of Kaśyapa, is the mother of the Dānavas, including Vipracitti.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "daksha", "verified", [BP("6", "6"), VP("1", "15")]),
      rel("spouse", "kashyapa", "verified", [BP("6", "6")]),
      rel("sister", "aditi", "verified", [BP("6", "6")]),
      rel("sister", "diti", "verified", [BP("6", "6")]),
      rel("son", "vipracitti", "verified", [BP("6", "6"), VP("1", "21")]),
      rel("son", "puloman", "traditional", [VP("1", "21")], "Listed among Danu's sons in Viṣṇu Purāṇa."),
      rel("son", "namuci", "traditional", [VP("1", "21"), MB("Udyoga Parva")], "Dānava slain in Indra narratives; parentage via Danu in Purāṇic lists."),
      rel("son", "shambara", "traditional", [VP("1", "21")]),
      rel("son", "maya-danava", "traditional", [VP("1", "21"), MB("Ādi Parva")], "Maya the architect; counted a Dānava in epic usage."),
    ],
    scriptureSources: [BP("6", "6"), VP("1", "21")],
  }),
  p({
    id: "kadru",
    name: "Kadrū",
    englishName: "Kadru",
    sanskritName: "कद्रू",
    gender: "female",
    category: "naga",
    era: "creation",
    dynasty: "naga",
    epithet: "Mother of the Nāgas",
    description: "Kadrū, daughter of Dakṣa and wife of Kaśyapa, is the mother of the serpent race (Nāgas), including Ananta, Vāsuki and Takṣaka.",
    primaryScripture: "Mahābhārata",
    importance: 5,
    relationships: [
      rel("father", "daksha", "verified", [BP("6", "6"), MB("Ādi Parva", "16")]),
      rel("spouse", "kashyapa", "verified", [MB("Ādi Parva", "16"), BP("6", "6")]),
      rel("son", "ananta", "verified", [BP("5", "25"), BP("6", "6")]),
      rel("son", "vasuki", "verified", [MB("Ādi Parva", "16–35"), BP("6", "6")]),
      rel("son", "takshaka", "verified", [MB("Ādi Parva", "3"), BP("6", "6")]),
      rel("son", "karkotaka", "traditional", [MB("Ādi Parva"), BP("6", "6")]),
      rel("son", "padma-naga", "traditional", [BP("6", "6")], "Named among principal Nāgas."),
      rel("son", "mahapadma-naga", "traditional", [BP("6", "6")]),
      rel("son", "kulika-naga", "traditional", [BP("6", "6")]),
      rel("son", "shankha-naga", "traditional", [BP("6", "6")]),
    ],
    scriptureSources: [MB("Ādi Parva", "16"), BP("5", "25"), BP("6", "6")],
  }),
];

export const DAITYAS: PersonDraft[] = [
  p({
    id: "hiranyakashipu",
    name: "Hiraṇyakaśipu",
    englishName: "Hiranyakashipu",
    sanskritName: "हिरण्यकशिपु",
    aliases: ["Hiranyakasipu"],
    gender: "male",
    category: "daitya",
    era: "satya-yuga",
    dynasty: "daitya",
    epithet: "Daitya king slain by Narasiṃha",
    description:
      "Hiraṇyakaśipu, son of Kaśyapa and Diti, persecuted his son Prahlāda for devotion to Viṣṇu and was destroyed by the Narasiṃha avatāra.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    imagePlaceholder: "🦁",
    relationships: [
      rel("father", "kashyapa", "verified", [BP("7", "2")]),
      rel("mother", "diti", "verified", [BP("7", "2"), BP("3", "14")]),
      rel("brother", "hiranyaksha", "verified", [BP("3", "14")]),
      rel("sister", "simhika", "verified", [BP("6", "18")]),
      rel("son", "prahlada", "verified", [BP("7", "4–10")]),
    ],
    scriptureSources: [BP("7")],
  }),
  p({
    id: "hiranyaksha",
    name: "Hiraṇyākṣa",
    englishName: "Hiranyaksha",
    sanskritName: "हिरण्याक्ष",
    aliases: ["Hiranyaksa"],
    gender: "male",
    category: "daitya",
    era: "satya-yuga",
    dynasty: "daitya",
    epithet: "Daitya slain by Varāha",
    description:
      "Hiraṇyākṣa, twin brother of Hiraṇyakaśipu, dragged the earth into the waters and was slain by Viṣṇu as Varāha.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    imagePlaceholder: "🐗",
    relationships: [
      rel("father", "kashyapa", "verified", [BP("3", "14")]),
      rel("mother", "diti", "verified", [BP("3", "14")]),
      rel("brother", "hiranyakashipu", "verified", [BP("3", "14")]),
    ],
    scriptureSources: [BP("3", "14–19")],
  }),
  p({
    id: "simhika",
    name: "Siṃhikā",
    englishName: "Simhika",
    sanskritName: "सिंहिका",
    aliases: ["Simhika"],
    gender: "female",
    category: "daitya",
    era: "satya-yuga",
    dynasty: "daitya",
    epithet: "Daughter of Diti; mother of Rāhu",
    description:
      "Siṃhikā, daughter of Diti, married the Dānava Vipracitti and bore Rāhu — a cross-lineage birth recorded in the Bhāgavata.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    relationships: [
      rel("father", "kashyapa", "verified", [BP("6", "18")]),
      rel("mother", "diti", "verified", [BP("6", "18")]),
      rel("brother", "hiranyakashipu", "verified", [BP("6", "18")]),
      rel("spouse", "vipracitti", "verified", [BP("6", "18"), BP("8", "10")]),
      rel("son", "rahu", "verified", [BP("6", "18"), BP("8", "9–10")]),
    ],
    scriptureSources: [BP("6", "18"), BP("8", "9–10")],
    notes: "Rāhu's mother is Daitya (Siṃhikā); his father is Dānava (Vipracitti).",
  }),
  p({
    id: "prahlada",
    name: "Prahlāda",
    englishName: "Prahlada",
    sanskritName: "प्रह्लाद",
    aliases: ["Prahlad"],
    gender: "male",
    category: "daitya",
    era: "satya-yuga",
    dynasty: "daitya",
    epithet: "Devotee-prince among the Daityas",
    description:
      "Prahlāda, son of Hiraṇyakaśipu, remained devoted to Viṣṇu despite persecution — the paradigm of steadfast bhakti.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    imagePlaceholder: "🙏",
    relationships: [
      rel("father", "hiranyakashipu", "verified", [BP("7", "4")]),
      rel("son", "virocana", "verified", [BP("8", "15"), VP("1", "21")]),
    ],
    scriptureSources: [BP("7")],
    relatedVerses: [{ workCode: "bg", publicId: "bg.10.30", label: "Among Daityas I am Prahlāda" }],
  }),
  p({
    id: "virocana",
    name: "Virocana",
    englishName: "Virocana",
    sanskritName: "विरोचन",
    gender: "male",
    category: "daitya",
    era: "satya-yuga",
    dynasty: "daitya",
    epithet: "Son of Prahlāda; father of Bali",
    description: "Virocana is the son of Prahlāda and father of the generous Daitya king Bali (Mahābali).",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 3,
    relationships: [
      rel("father", "prahlada", "verified", [BP("8", "15"), VP("1", "21")]),
      rel("son", "bali", "verified", [BP("8", "15–23")]),
    ],
    scriptureSources: [BP("8", "15"), VP("1", "21")],
  }),
  p({
    id: "bali",
    name: "Bali",
    englishName: "Bali",
    sanskritName: "बलि",
    aliases: ["Mahabali", "Mahābali"],
    gender: "male",
    category: "daitya",
    era: "treta-yuga",
    dynasty: "daitya",
    epithet: "Daitya king of the Vāmana episode",
    description:
      "Bali, grandson of Prahlāda, conquered the three worlds. Viṣṇu as Vāmana requested three paces of land; Bali's gift sent him to Pātāla while honouring his vow.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    imagePlaceholder: "🦶",
    relationships: [
      rel("father", "virocana", "verified", [BP("8", "15")]),
      rel("son", "bana", "verified", [BP("10", "62"), HV("Viṣṇu Parva")], "Bāṇāsura, devotee of Śiva, son of Bali."),
    ],
    scriptureSources: [BP("8", "15–23")],
  }),
  p({
    id: "bana",
    name: "Bāṇa",
    englishName: "Bana",
    sanskritName: "बाण",
    aliases: ["Banasura", "Bāṇāsura"],
    gender: "male",
    category: "daitya",
    era: "dvapara-yuga",
    dynasty: "daitya",
    epithet: "Thousand-armed Daitya; son of Bali",
    description:
      "Bāṇa (Bāṇāsura), son of Bali, is a devotee of Śiva whose conflict with Kṛṣṇa is narrated in the Bhāgavata and Harivaṃśa.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    relationships: [rel("father", "bali", "verified", [BP("10", "62"), HV("Viṣṇu Parva")])],
    scriptureSources: [BP("10", "62–63"), HV("Viṣṇu Parva")],
  }),
  p({
    id: "rahu",
    name: "Rāhu",
    englishName: "Rahu",
    sanskritName: "राहु",
    gender: "male",
    category: "daitya",
    era: "eternal",
    dynasty: "daitya",
    epithet: "Eclipse-graha; son of Siṃhikā",
    description:
      "Rāhu is the son of Siṃhikā and Vipracitti. After the churning of the ocean he became an immortal eclipse-graha when severed by Viṣṇu's discus.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    relationships: [
      rel("mother", "simhika", "verified", [BP("6", "18"), BP("8", "9–10")]),
      rel("father", "vipracitti", "verified", [BP("6", "18"), BP("8", "10")]),
    ],
    scriptureSources: [BP("8", "9–10")],
    notes: "Cross-lineage: Daitya mother (Siṃhikā) + Dānava father (Vipracitti).",
  }),
];

export const DANAVAS: PersonDraft[] = [
  p({
    id: "vipracitti",
    name: "Vipracitti",
    englishName: "Vipracitti",
    sanskritName: "विप्रचित्ति",
    aliases: ["Viprachitti"],
    gender: "male",
    category: "danava",
    era: "satya-yuga",
    dynasty: "danava",
    epithet: "Dānava; husband of Siṃhikā; father of Rāhu",
    description: "Vipracitti, a son of Danu, married Siṃhikā and fathered Rāhu.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 4,
    relationships: [
      rel("mother", "danu", "verified", [BP("6", "6"), VP("1", "21")]),
      rel("father", "kashyapa", "verified", [BP("6", "6")]),
      rel("spouse", "simhika", "verified", [BP("6", "18")]),
      rel("son", "rahu", "verified", [BP("6", "18"), BP("8", "10")]),
    ],
    scriptureSources: [BP("6", "6"), BP("6", "18")],
  }),
  p({
    id: "puloman",
    name: "Puloman",
    englishName: "Puloman",
    sanskritName: "पुलोमन्",
    gender: "male",
    category: "danava",
    era: "creation",
    dynasty: "danava",
    epithet: "Dānava listed among Danu's sons",
    description: "Puloman appears in Purāṇic lists of Danu's sons (Viṣṇu Purāṇa).",
    primaryScripture: "Viṣṇu Purāṇa",
    importance: 2,
    relationships: [
      rel("mother", "danu", "traditional", [VP("1", "21")]),
      rel("father", "kashyapa", "traditional", [VP("1", "21")]),
    ],
    scriptureSources: [VP("1", "21")],
  }),
  p({
    id: "namuci",
    name: "Namuci",
    englishName: "Namuci",
    sanskritName: "नमुचि",
    gender: "male",
    category: "danava",
    era: "creation",
    dynasty: "danava",
    epithet: "Dānava adversary of Indra",
    description: "Namuci is a Dānava associated with Indra's battles in epic and Purāṇic memory; listed among Danu's progeny in Viṣṇu Purāṇa.",
    primaryScripture: "Viṣṇu Purāṇa",
    importance: 2,
    relationships: [
      rel("mother", "danu", "traditional", [VP("1", "21")]),
      rel("father", "kashyapa", "traditional", [VP("1", "21")]),
    ],
    scriptureSources: [VP("1", "21"), MB("Udyoga Parva")],
  }),
  p({
    id: "shambara",
    name: "Śambara",
    englishName: "Shambara",
    sanskritName: "शम्बर",
    aliases: ["Sambara"],
    gender: "male",
    category: "danava",
    era: "creation",
    dynasty: "danava",
    epithet: "Dānava of Vedic and Purāṇic conflict narratives",
    description: "Śambara is counted among Danu's sons in the Viṣṇu Purāṇa and appears as an adversary in older Indra lore.",
    primaryScripture: "Viṣṇu Purāṇa",
    importance: 2,
    relationships: [
      rel("mother", "danu", "traditional", [VP("1", "21")]),
      rel("father", "kashyapa", "traditional", [VP("1", "21")]),
    ],
    scriptureSources: [VP("1", "21")],
  }),
  p({
    id: "maya-danava",
    name: "Maya",
    englishName: "Maya Danava",
    sanskritName: "मय",
    aliases: ["Mayasura", "Maya Dānava", "Maya Danava"],
    gender: "male",
    category: "danava",
    era: "dvapara-yuga",
    dynasty: "danava",
    epithet: "Architect of the Dānavas; builder of the hall at Indraprastha",
    description:
      "Maya is the divine architect associated with the Dānava/asura side in the Mahābhārata; he builds the wondrous sabhā for the Pāṇḍavas after being spared by Arjuna and Kṛṣṇa.",
    primaryScripture: "Mahābhārata",
    importance: 4,
    relationships: [
      rel("mother", "danu", "traditional", [VP("1", "21")], "Purāṇic lists place Maya among Danu's line; the epic treats him as Dānava/asura architect."),
      rel("father", "kashyapa", "traditional", [VP("1", "21")]),
    ],
    scriptureSources: [MB("Ādi Parva", "228–233"), VP("1", "21")],
  }),
];

export const DEVAS: PersonDraft[] = [
  p({
    id: "indra",
    name: "Indra",
    englishName: "Indra",
    sanskritName: "इन्द्र",
    aliases: ["Sakrada", "Śakra", "Purandara", "Devendra"],
    gender: "male",
    category: "deva",
    era: "eternal",
    dynasty: "aditya",
    epithet: "King of the Devas; an Āditya",
    description:
      "Indra, son of Kaśyapa and Aditi, is sovereign of Svarga and foremost among the Ādityas in epic and Purāṇic narrative.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    imagePlaceholder: "⚡",
    relationships: [
      rel("father", "kashyapa", "verified", [BP("6", "18"), VP("1", "15")]),
      rel("mother", "aditi", "verified", [BP("6", "18")]),
      rel("brother", "vivasvan", "verified", [BP("6", "6")]),
    ],
    scriptureSources: [BP("6", "18"), VP("1", "15")],
    relatedVerses: [{ workCode: "bg", publicId: "bg.10.22", label: "Among gods I am Indra (Vāsava)" }],
  }),
  p({
    id: "vivasvan",
    name: "Vivasvān",
    englishName: "Vivasvan",
    sanskritName: "विवस्वन्",
    aliases: ["Vivasvat", "Surya", "Sūrya", "Aditya"],
    gender: "male",
    category: "deva",
    era: "eternal",
    dynasty: "suryavamsa",
    epithet: "The Sun; an Āditya; source of the Solar Dynasty",
    description:
      "Vivasvān is an Āditya, son of Kaśyapa and Aditi. Through him descends Vaivasvata Manu and the Solar (Sūryavaṃśa) line. The Gītā recalls that Kṛṣṇa taught yoga to Vivasvān.",
    primaryScripture: "Bhagavad Gītā",
    importance: 5,
    imagePlaceholder: "☀️",
    relationships: [
      rel("father", "kashyapa", "verified", [BP("6", "6"), VP("1", "15")]),
      rel("mother", "aditi", "verified", [BP("6", "6")]),
      rel("brother", "indra", "verified", [BP("6", "6")]),
      rel("son", "vaivasvata-manu", "verified", [BP("8", "24"), VP("3", "1"), BG("4")], "Vaivasvata Manu is son of Vivasvān."),
    ],
    scriptureSources: [BP("6", "6"), BG("4"), VP("3", "1")],
    relatedVerses: [{ workCode: "bg", publicId: "bg.4.1", label: "I taught this yoga to Vivasvān" }],
  }),
  p({
    id: "varuna",
    name: "Varuṇa",
    englishName: "Varuna",
    sanskritName: "वरुण",
    gender: "male",
    category: "deva",
    era: "eternal",
    dynasty: "aditya",
    epithet: "Āditya; lord of waters and cosmic order",
    description: "Varuṇa is counted among the Ādityas, sons of Aditi, in Purāṇic lists; he governs waters and ṛta in Vedic memory.",
    primaryScripture: "Viṣṇu Purāṇa",
    importance: 3,
    relationships: [
      rel("father", "kashyapa", "traditional", [VP("1", "15"), BP("6", "6")]),
      rel("mother", "aditi", "traditional", [VP("1", "15")]),
    ],
    scriptureSources: [VP("1", "15"), BP("6", "6")],
  }),
  p({
    id: "mitra",
    name: "Mitra",
    englishName: "Mitra",
    sanskritName: "मित्र",
    gender: "male",
    category: "deva",
    era: "eternal",
    dynasty: "aditya",
    epithet: "Āditya; companion of Varuṇa in Vedic liturgy",
    description: "Mitra is listed among the Ādityas born of Aditi in the Viṣṇu and Bhāgavata Purāṇas.",
    primaryScripture: "Viṣṇu Purāṇa",
    importance: 2,
    relationships: [
      rel("father", "kashyapa", "traditional", [VP("1", "15")]),
      rel("mother", "aditi", "traditional", [VP("1", "15")]),
    ],
    scriptureSources: [VP("1", "15")],
  }),
  p({
    id: "aryaman",
    name: "Aryaman",
    englishName: "Aryaman",
    sanskritName: "अर्यमन्",
    gender: "male",
    category: "deva",
    era: "eternal",
    dynasty: "aditya",
    epithet: "Āditya",
    description: "Aryaman is named among the Ādityas in Purāṇic catalogues of Aditi's sons.",
    primaryScripture: "Viṣṇu Purāṇa",
    importance: 2,
    relationships: [
      rel("father", "kashyapa", "traditional", [VP("1", "15")]),
      rel("mother", "aditi", "traditional", [VP("1", "15")]),
    ],
    scriptureSources: [VP("1", "15")],
  }),
  p({
    id: "bhaga",
    name: "Bhaga",
    englishName: "Bhaga",
    sanskritName: "भग",
    gender: "male",
    category: "deva",
    era: "eternal",
    dynasty: "aditya",
    epithet: "Āditya",
    description: "Bhaga is listed among Aditi's Āditya sons in the Viṣṇu Purāṇa.",
    primaryScripture: "Viṣṇu Purāṇa",
    importance: 2,
    relationships: [
      rel("father", "kashyapa", "traditional", [VP("1", "15")]),
      rel("mother", "aditi", "traditional", [VP("1", "15")]),
    ],
    scriptureSources: [VP("1", "15")],
  }),
  p({
    id: "pushan",
    name: "Pūṣan",
    englishName: "Pushan",
    sanskritName: "पूषन्",
    aliases: ["Pusan"],
    gender: "male",
    category: "deva",
    era: "eternal",
    dynasty: "aditya",
    epithet: "Āditya; nourisher",
    description: "Pūṣan is counted among the Ādityas in Purāṇic lists of Aditi's sons.",
    primaryScripture: "Viṣṇu Purāṇa",
    importance: 2,
    relationships: [
      rel("father", "kashyapa", "traditional", [VP("1", "15")]),
      rel("mother", "aditi", "traditional", [VP("1", "15")]),
    ],
    scriptureSources: [VP("1", "15")],
  }),
  p({
    id: "savitr",
    name: "Savitṛ",
    englishName: "Savitr",
    sanskritName: "सवितृ",
    aliases: ["Savita", "Savitā"],
    gender: "male",
    category: "deva",
    era: "eternal",
    dynasty: "aditya",
    epithet: "Āditya; the impeller",
    description: "Savitṛ is named among the Ādityas; in some traditions he is closely identified with aspects of the solar deity.",
    primaryScripture: "Viṣṇu Purāṇa",
    importance: 2,
    relationships: [
      rel("father", "kashyapa", "traditional", [VP("1", "15")]),
      rel("mother", "aditi", "traditional", [VP("1", "15")]),
    ],
    scriptureSources: [VP("1", "15")],
  }),
];

export const NAGAS: PersonDraft[] = [
  p({
    id: "ananta",
    name: "Ananta",
    englishName: "Ananta",
    sanskritName: "अनन्त",
    aliases: ["Shesha", "Śeṣa", "Sesha", "Adi Shesha", "Ādiśeṣa"],
    gender: "male",
    category: "naga",
    era: "eternal",
    dynasty: "naga",
    epithet: "Endless serpent; bed of Viṣṇu",
    description:
      "Ananta (Śeṣa) is the foremost Nāga, son of Kaśyapa and Kadrū. He supports the worlds and serves as Viṣṇu's couch.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    imagePlaceholder: "🐍",
    relationships: [
      rel("father", "kashyapa", "verified", [BP("5", "25"), BP("6", "6")]),
      rel("mother", "kadru", "verified", [BP("5", "25"), MB("Ādi Parva", "16")]),
      rel("brother", "vasuki", "verified", [BP("6", "6")]),
    ],
    scriptureSources: [BP("5", "25"), BP("6", "6")],
  }),
  p({
    id: "vasuki",
    name: "Vāsuki",
    englishName: "Vasuki",
    sanskritName: "वासुकि",
    gender: "male",
    category: "naga",
    era: "eternal",
    dynasty: "naga",
    epithet: "Nāga king; rope in the churning of the ocean",
    description:
      "Vāsuki, son of Kaśyapa and Kadrū, is the Nāga used as the churning-rope in the Samudra Manthana.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 5,
    relationships: [
      rel("father", "kashyapa", "verified", [BP("6", "6"), MB("Ādi Parva", "16")]),
      rel("mother", "kadru", "verified", [MB("Ādi Parva", "16")]),
      rel("brother", "ananta", "verified", [BP("6", "6")]),
      rel("brother", "takshaka", "verified", [MB("Ādi Parva", "16–35")]),
    ],
    scriptureSources: [BP("8", "7"), MB("Ādi Parva", "16")],
  }),
  p({
    id: "takshaka",
    name: "Takṣaka",
    englishName: "Takshaka",
    sanskritName: "तक्षक",
    aliases: ["Taksaka"],
    gender: "male",
    category: "naga",
    era: "dvapara-yuga",
    dynasty: "naga",
    epithet: "Nāga who bites Parīkṣit",
    description:
      "Takṣaka, a principal Nāga son of Kadrū, appears in the Mahābhārata as the serpent who bites King Parīkṣit.",
    primaryScripture: "Mahābhārata",
    importance: 4,
    relationships: [
      rel("father", "kashyapa", "verified", [BP("6", "6"), MB("Ādi Parva", "3")]),
      rel("mother", "kadru", "verified", [MB("Ādi Parva", "16")]),
      rel("brother", "vasuki", "verified", [MB("Ādi Parva", "16")]),
    ],
    scriptureSources: [MB("Ādi Parva", "3"), MB("Ādi Parva", "43")],
  }),
  p({
    id: "karkotaka",
    name: "Karkoṭaka",
    englishName: "Karkotaka",
    sanskritName: "कर्कोटक",
    gender: "male",
    category: "naga",
    era: "dvapara-yuga",
    dynasty: "naga",
    epithet: "Principal Nāga of Kadrū's line",
    description: "Karkoṭaka is named among the great Nāgas born of Kadrū in epic and Purāṇic lists.",
    primaryScripture: "Mahābhārata",
    importance: 3,
    relationships: [
      rel("father", "kashyapa", "traditional", [BP("6", "6"), MB("Ādi Parva")]),
      rel("mother", "kadru", "traditional", [MB("Ādi Parva"), BP("6", "6")]),
    ],
    scriptureSources: [MB("Ādi Parva"), BP("6", "6")],
  }),
  p({
    id: "padma-naga",
    name: "Padma",
    englishName: "Padma",
    sanskritName: "पद्म",
    gender: "male",
    category: "naga",
    era: "eternal",
    dynasty: "naga",
    epithet: "One of the principal Nāgas",
    description: "Padma is listed among the principal Nāgas in Bhāgavata Purāṇa catalogues of Kadrū's sons.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 2,
    relationships: [
      rel("father", "kashyapa", "traditional", [BP("6", "6")]),
      rel("mother", "kadru", "traditional", [BP("6", "6")]),
    ],
    scriptureSources: [BP("6", "6")],
  }),
  p({
    id: "mahapadma-naga",
    name: "Mahāpadma",
    englishName: "Mahapadma",
    sanskritName: "महापद्म",
    gender: "male",
    category: "naga",
    era: "eternal",
    dynasty: "naga",
    epithet: "Principal Nāga",
    description: "Mahāpadma appears among named Nāga princes in Purāṇic lists of the serpent race.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 2,
    relationships: [
      rel("father", "kashyapa", "traditional", [BP("6", "6")]),
      rel("mother", "kadru", "traditional", [BP("6", "6")]),
    ],
    scriptureSources: [BP("6", "6")],
  }),
  p({
    id: "kulika-naga",
    name: "Kulika",
    englishName: "Kulika",
    sanskritName: "कुलिक",
    gender: "male",
    category: "naga",
    era: "eternal",
    dynasty: "naga",
    epithet: "Principal Nāga",
    description: "Kulika is counted among the great Nāgas in traditional lists of Kadrū's progeny.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 2,
    relationships: [
      rel("father", "kashyapa", "traditional", [BP("6", "6")]),
      rel("mother", "kadru", "traditional", [BP("6", "6")]),
    ],
    scriptureSources: [BP("6", "6")],
  }),
  p({
    id: "shankha-naga",
    name: "Śaṅkha",
    englishName: "Shankha",
    sanskritName: "शङ्ख",
    aliases: ["Sankha"],
    gender: "male",
    category: "naga",
    era: "eternal",
    dynasty: "naga",
    epithet: "Principal Nāga",
    description: "Śaṅkha is named among the principal Nāgas of Kadrū's line in the Bhāgavata.",
    primaryScripture: "Bhāgavata Purāṇa",
    importance: 2,
    relationships: [
      rel("father", "kashyapa", "traditional", [BP("6", "6")]),
      rel("mother", "kadru", "traditional", [BP("6", "6")]),
    ],
    scriptureSources: [BP("6", "6")],
  }),
];

export const RAKSHASAS: PersonDraft[] = [
  p({
    id: "visravas",
    name: "Viśravas",
    englishName: "Visravas",
    sanskritName: "विश्रवस्",
    aliases: ["Visrava", "Vishravas"],
    gender: "male",
    category: "rishi",
    era: "treta-yuga",
    dynasty: "rakshasa",
    epithet: "Son of Pulastya; father of Kubera and Rāvaṇa",
    description:
      "Viśravas, son of Pulastya, fathers Kubera by Ilavilā (Devavarṇinī) and Rāvaṇa, Kumbhakarṇa, Vibhīṣaṇa and Śūrpaṇakhā by Kaikasī.",
    primaryScripture: "Rāmāyaṇa",
    importance: 5,
    relationships: [
      rel("father", "pulastya", "verified", [RM("Uttara Kāṇḍa", "2–9"), BP("4", "1")]),
      rel("son", "kubera", "verified", [RM("Uttara Kāṇḍa", "3–9"), BP("4", "1")]),
      rel("son", "ravana", "verified", [RM("Uttara Kāṇḍa", "9"), RM("Bāla Kāṇḍa")]),
      rel("son", "kumbhakarna", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("son", "vibhishana", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("daughter", "surpanakha", "verified", [RM("Uttara Kāṇḍa", "9"), RM("Araṇya Kāṇḍa")]),
      rel("spouse", "kaikasi", "verified", [RM("Uttara Kāṇḍa", "9")]),
    ],
    scriptureSources: [RM("Uttara Kāṇḍa", "2–9")],
  }),
  p({
    id: "kaikasi",
    name: "Kaikasī",
    englishName: "Kaikasi",
    sanskritName: "कैकसी",
    aliases: ["Kaikasi"],
    gender: "female",
    category: "rakshasa",
    era: "treta-yuga",
    dynasty: "rakshasa",
    epithet: "Mother of Rāvaṇa and his siblings",
    description: "Kaikasī, daughter of the rākṣasa Sumālin, is the wife of Viśravas and mother of Rāvaṇa, Kumbhakarṇa, Vibhīṣaṇa and Śūrpaṇakhā.",
    primaryScripture: "Rāmāyaṇa",
    importance: 4,
    relationships: [
      rel("spouse", "visravas", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("son", "ravana", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("son", "kumbhakarna", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("son", "vibhishana", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("daughter", "surpanakha", "verified", [RM("Uttara Kāṇḍa", "9")]),
    ],
    scriptureSources: [RM("Uttara Kāṇḍa", "9")],
  }),
  p({
    id: "kubera",
    name: "Kubera",
    englishName: "Kubera",
    sanskritName: "कुबेर",
    aliases: ["Vaisravana", "Vaiśravaṇa", "Kuvera"],
    gender: "male",
    category: "yaksha",
    era: "treta-yuga",
    dynasty: "yaksha",
    epithet: "Lord of Yakṣas; half-brother of Rāvaṇa",
    description:
      "Kubera (Vaiśravaṇa), son of Viśravas, is lord of the Yakṣas and guardian of wealth. He first ruled Laṅkā before Rāvaṇa seized it.",
    primaryScripture: "Rāmāyaṇa",
    importance: 5,
    relationships: [
      rel("father", "visravas", "verified", [RM("Uttara Kāṇḍa", "3–9"), BP("4", "1")]),
      rel("brother", "ravana", "verified", [RM("Uttara Kāṇḍa", "9")], "Half-brothers — different mothers."),
    ],
    scriptureSources: [RM("Uttara Kāṇḍa", "3–9"), BP("4", "1")],
    notes: "Categorised as Yakṣa (lord of Yakṣas), not Rākṣasa — though of the same paternal line.",
  }),
  p({
    id: "ravana",
    name: "Rāvaṇa",
    englishName: "Ravana",
    sanskritName: "रावण",
    aliases: ["Dashagriva", "Daśagrīva", "Lankesha", "Laṅkeśa"],
    gender: "male",
    category: "rakshasa",
    era: "treta-yuga",
    dynasty: "rakshasa",
    epithet: "Ten-headed king of Laṅkā",
    description:
      "Rāvaṇa, son of Viśravas and Kaikasī, rules Laṅkā, abducts Sītā, and is slain by Rāma — the central antagonist of the Rāmāyaṇa.",
    primaryScripture: "Rāmāyaṇa",
    importance: 5,
    imagePlaceholder: "👑",
    relationships: [
      rel("father", "visravas", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("mother", "kaikasi", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("brother", "kumbhakarna", "verified", [RM("Uttara Kāṇḍa", "9"), RM("Yuddha Kāṇḍa")]),
      rel("brother", "vibhishana", "verified", [RM("Uttara Kāṇḍa", "9"), RM("Yuddha Kāṇḍa")]),
      rel("sister", "surpanakha", "verified", [RM("Araṇya Kāṇḍa"), RM("Uttara Kāṇḍa", "9")]),
      rel("brother", "kubera", "verified", [RM("Uttara Kāṇḍa", "9")], "Half-brother."),
      rel("son", "indrajit", "verified", [RM("Yuddha Kāṇḍa")], "Indrajit (Meghanāda), son of Rāvaṇa."),
    ],
    scriptureSources: [RM("Uttara Kāṇḍa", "9"), RM("Yuddha Kāṇḍa")],
  }),
  p({
    id: "kumbhakarna",
    name: "Kumbhakarṇa",
    englishName: "Kumbhakarna",
    sanskritName: "कुम्भकर्ण",
    gender: "male",
    category: "rakshasa",
    era: "treta-yuga",
    dynasty: "rakshasa",
    epithet: "Brother of Rāvaṇa; giant warrior of Laṅkā",
    description: "Kumbhakarṇa, son of Viśravas and Kaikasī, is famed for his vast size, long sleep, and death in battle against Rāma's army.",
    primaryScripture: "Rāmāyaṇa",
    importance: 4,
    relationships: [
      rel("father", "visravas", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("mother", "kaikasi", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("brother", "ravana", "verified", [RM("Yuddha Kāṇḍa")]),
      rel("brother", "vibhishana", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("sister", "surpanakha", "verified", [RM("Uttara Kāṇḍa", "9")]),
    ],
    scriptureSources: [RM("Uttara Kāṇḍa", "9"), RM("Yuddha Kāṇḍa")],
  }),
  p({
    id: "vibhishana",
    name: "Vibhīṣaṇa",
    englishName: "Vibhishana",
    sanskritName: "विभीषण",
    aliases: ["Vibhisana"],
    gender: "male",
    category: "rakshasa",
    era: "treta-yuga",
    dynasty: "rakshasa",
    epithet: "Dharmic brother of Rāvaṇa; ally of Rāma",
    description:
      "Vibhīṣaṇa, son of Viśravas and Kaikasī, counsels dharma, defects to Rāma, and is crowned king of Laṅkā after Rāvaṇa's fall.",
    primaryScripture: "Rāmāyaṇa",
    importance: 5,
    relationships: [
      rel("father", "visravas", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("mother", "kaikasi", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("brother", "ravana", "verified", [RM("Yuddha Kāṇḍa")]),
      rel("brother", "kumbhakarna", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("sister", "surpanakha", "verified", [RM("Uttara Kāṇḍa", "9")]),
    ],
    scriptureSources: [RM("Uttara Kāṇḍa", "9"), RM("Yuddha Kāṇḍa")],
  }),
  p({
    id: "surpanakha",
    name: "Śūrpaṇakhā",
    englishName: "Surpanakha",
    sanskritName: "शूर्पणखा",
    aliases: ["Surpanakha", "Shurpanakha"],
    gender: "female",
    category: "rakshasa",
    era: "treta-yuga",
    dynasty: "rakshasa",
    epithet: "Sister of Rāvaṇa",
    description:
      "Śūrpaṇakhā, daughter of Viśravas and Kaikasī, encounters Rāma and Lakṣmaṇa in the Daṇḍaka forest — an episode that precipitates the war with Laṅkā.",
    primaryScripture: "Rāmāyaṇa",
    importance: 4,
    relationships: [
      rel("father", "visravas", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("mother", "kaikasi", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("brother", "ravana", "verified", [RM("Araṇya Kāṇḍa")]),
      rel("brother", "kumbhakarna", "verified", [RM("Uttara Kāṇḍa", "9")]),
      rel("brother", "vibhishana", "verified", [RM("Uttara Kāṇḍa", "9")]),
    ],
    scriptureSources: [RM("Araṇya Kāṇḍa"), RM("Uttara Kāṇḍa", "9")],
  }),
  p({
    id: "indrajit",
    name: "Indrajit",
    englishName: "Indrajit",
    sanskritName: "इन्द्रजित्",
    aliases: ["Meghanada", "Meghanāda"],
    gender: "male",
    category: "rakshasa",
    era: "treta-yuga",
    dynasty: "rakshasa",
    epithet: "Son of Rāvaṇa; conqueror of Indra",
    description: "Indrajit (Meghanāda), son of Rāvaṇa, is the foremost warrior of Laṅkā, slain by Lakṣmaṇa in the Yuddha Kāṇḍa.",
    primaryScripture: "Rāmāyaṇa",
    importance: 4,
    relationships: [rel("father", "ravana", "verified", [RM("Yuddha Kāṇḍa")])],
    scriptureSources: [RM("Yuddha Kāṇḍa")],
  }),
];

export const YAKSHAS: PersonDraft[] = [
  // Kubera is defined in RAKSHASAS file section (yaksha category) — listed here only via module membership.
];

export const GANDHARVAS: PersonDraft[] = [
  p({
    id: "chitraratha",
    name: "Citraratha",
    englishName: "Chitraratha",
    sanskritName: "चित्ररथ",
    gender: "male",
    category: "gandharva",
    era: "dvapara-yuga",
    dynasty: "gandharva",
    epithet: "Gandharva king mentioned in the Mahābhārata",
    description:
      "Citraratha is a Gandharva who encounters Arjuna; the Gītā names him among Kṛṣṇa's vibhūtis.",
    primaryScripture: "Mahābhārata",
    importance: 3,
    relationships: [],
    scriptureSources: [MB("Ādi Parva"), BG("10")],
    relatedVerses: [{ workCode: "bg", publicId: "bg.10.26", label: "Among Gandharvas I am Citraratha" }],
    notes: "Parentage is not securely fixed in the primary epic passages used here; listed as a named Gandharva without invented ancestors.",
  }),
];
