/**
 * Dense Mahābhārata / Purāṇa / Gītā geography for the Atlas layer.
 * Coordinates are traditional educational placements (not surveyed borders).
 * Merges by entity id in rebuild — does not invent unverified person edges.
 */

type Cite = { work: string; section?: string; chapter?: string; note?: string };
type AtlasMeta = {
  latitude: number;
  longitude: number;
  modernLocation: string;
  kingdom?: string;
  scripturalSignificance?: string;
  atlasCategory?:
    | "kingdom"
    | "city"
    | "forest"
    | "battlefield"
    | "ashrama"
    | "river"
    | "mountain"
    | "pilgrimage"
    | "sacred";
};

type Entity = {
  id: string;
  slug: string;
  kind: string;
  name: string;
  englishName: string;
  iastName: string;
  aliases: string[];
  summary: string;
  description: string;
  primaryScripture: string;
  scriptureSources: Cite[];
  tags: string[];
  categories: string[];
  importance: number;
  seo: { title?: string };
  atlas: AtlasMeta;
  status: "published";
  schemaVersion: number;
  era: string;
  variantTraditions: [];
};

const MB = (parva: string, note?: string): Cite => ({
  work: "Mahābhārata",
  section: parva,
  ...(note ? { note } : {}),
});
const BP = (sk: string): Cite => ({
  work: "Bhāgavata Purāṇa",
  section: `Skandha ${sk}`,
});
const BG = (ch: string): Cite => ({ work: "Bhagavad Gītā", chapter: ch });

function e(
  p: Omit<Entity, "status" | "schemaVersion" | "variantTraditions" | "era"> & {
    era?: string;
  },
): Entity {
  return {
    status: "published",
    schemaVersion: 1,
    era: p.era ?? "dvapara-yuga",
    variantTraditions: [],
    ...p,
  };
}

type PlaceRow = {
  id: string;
  slug: string;
  kind: string;
  name: string;
  englishName: string;
  iastName: string;
  aliases?: string[];
  summary: string;
  description?: string;
  lat: number;
  lng: number;
  modern: string;
  kingdom?: string;
  significance?: string;
  category: AtlasMeta["atlasCategory"];
  importance: number;
  tags?: string[];
  sources?: Cite[];
};

function fromRow(r: PlaceRow): Entity {
  return e({
    id: r.id,
    slug: r.slug,
    kind: r.kind,
    name: r.name,
    englishName: r.englishName,
    iastName: r.iastName,
    aliases: r.aliases ?? [],
    summary: r.summary,
    description:
      r.description ??
      `${r.summary} Placed approximately for educational atlas use.`,
    primaryScripture: "Mahābhārata",
    scriptureSources: r.sources ?? [MB("Sabhā Parva"), MB("Vana Parva")],
    tags: ["atlas", "mahabharata", ...(r.tags ?? [])],
    categories: [r.kind],
    importance: r.importance,
    seo: { title: r.name },
    atlas: {
      latitude: r.lat,
      longitude: r.lng,
      modernLocation: r.modern,
      ...(r.kingdom ? { kingdom: r.kingdom } : {}),
      ...(r.significance ? { scripturalSignificance: r.significance } : {}),
      atlasCategory: r.category,
    },
  });
}

/** Kingdoms, tribes, cities, tirthas named across digvijaya / pilgrimage lists. */
const ROWS: PlaceRow[] = [
  // —— Northwest ——
  {
    id: "kingdom.madra",
    slug: "madra",
    kind: "kingdom",
    name: "Madra",
    englishName: "Madra",
    iastName: "Madra",
    summary: "Northwestern realm of Mādrī.",
    lat: 32.5,
    lng: 74.5,
    modern: "Punjab / Sialkot region (traditional)",
    kingdom: "Madra",
    category: "kingdom",
    importance: 4,
    tags: ["madri"],
    sources: [MB("Ādi Parva")],
  },
  {
    id: "kingdom.bahlika",
    slug: "bahlika",
    kind: "kingdom",
    name: "Bāhlīka",
    englishName: "Bahlika",
    iastName: "Bāhlīka",
    aliases: ["Vahlika"],
    summary: "Northern kingdom allied to the Kurus.",
    lat: 34.0,
    lng: 72.0,
    modern: "Balkh / NW frontier (traditional)",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.trigarta",
    slug: "trigarta",
    kind: "kingdom",
    name: "Trigarta",
    englishName: "Trigarta",
    iastName: "Trigarta",
    summary: "Hill kingdom of Suśarmā; foe of Matsya.",
    lat: 32.0,
    lng: 76.0,
    modern: "Kangra / Jalandhar tract (traditional)",
    category: "kingdom",
    importance: 3,
    sources: [MB("Virāṭa Parva")],
  },
  {
    id: "kingdom.sindhu",
    slug: "sindhu-kingdom",
    kind: "kingdom",
    name: "Sindhu",
    englishName: "Sindhu",
    iastName: "Sindhu",
    summary: "Indus-side kingdom of Jayadratha.",
    lat: 26.5,
    lng: 68.5,
    modern: "Sindh (Pakistan)",
    kingdom: "Sindhu",
    category: "kingdom",
    importance: 4,
    tags: ["jayadratha"],
    sources: [MB("Vana Parva")],
  },
  {
    id: "kingdom.sauvira",
    slug: "sauvira",
    kind: "kingdom",
    name: "Sauvīra",
    englishName: "Sauvira",
    iastName: "Sauvīra",
    summary: "Realm paired with Sindhu in epic lists.",
    lat: 25.5,
    lng: 69.5,
    modern: "Lower Indus / Kutch fringe (traditional)",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.kekaya",
    slug: "kekaya",
    kind: "kingdom",
    name: "Kekaya",
    englishName: "Kekaya",
    iastName: "Kekaya",
    summary: "Northwestern clan-kingdom in digvijaya lists.",
    lat: 33.2,
    lng: 73.5,
    modern: "NW Punjab (traditional)",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.kashmira",
    slug: "kashmira",
    kind: "kingdom",
    name: "Kāśmīra",
    englishName: "Kashmira",
    iastName: "Kāśmīra",
    summary: "Himalayan valley kingdom.",
    lat: 34.0,
    lng: 74.8,
    modern: "Kashmir Valley",
    category: "kingdom",
    importance: 3,
  },

  // —— North / Gangetic ——
  {
    id: "city.ahicchatra",
    slug: "ahicchatra",
    kind: "city",
    name: "Ahicchatra",
    englishName: "Ahicchatra",
    iastName: "Ahicchatra",
    summary: "Northern Pañcāla capital.",
    lat: 28.37,
    lng: 79.12,
    modern: "Ramnagar / Bareilly region, UP",
    kingdom: "Pañcāla",
    category: "city",
    importance: 4,
    tags: ["capital"],
    sources: [MB("Ādi Parva")],
  },
  {
    id: "city.kampilya",
    slug: "kampilya",
    kind: "city",
    name: "Kāmpilya",
    englishName: "Kampilya",
    iastName: "Kāmpilya",
    summary: "Southern Pañcāla capital; Draupadī's city.",
    lat: 27.5,
    lng: 79.4,
    modern: "Farrukhabad region, UP (traditional)",
    kingdom: "Pañcāla",
    category: "city",
    importance: 5,
    tags: ["capital", "draupadi"],
    sources: [MB("Ādi Parva")],
  },
  {
    id: "city.mithila",
    slug: "mithila",
    kind: "city",
    name: "Mithilā",
    englishName: "Mithila",
    iastName: "Mithilā",
    summary: "Capital of Videha.",
    lat: 26.6,
    lng: 85.9,
    modern: "Janakpur / north Bihar (traditional)",
    kingdom: "Videha",
    category: "city",
    importance: 4,
    tags: ["capital"],
  },
  {
    id: "kingdom.videha",
    slug: "videha",
    kind: "kingdom",
    name: "Videha",
    englishName: "Videha",
    iastName: "Videha",
    summary: "East-Gangetic kingdom; Mithilā.",
    lat: 26.5,
    lng: 86.0,
    modern: "North Bihar / Terai",
    category: "kingdom",
    importance: 4,
  },
  {
    id: "city.shravasti",
    slug: "shravasti",
    kind: "city",
    name: "Śrāvastī",
    englishName: "Shravasti",
    iastName: "Śrāvastī",
    summary: "Kosala capital in many epic lists.",
    lat: 27.51,
    lng: 82.05,
    modern: "Shravasti, Uttar Pradesh",
    kingdom: "Kosala",
    category: "city",
    importance: 4,
    tags: ["capital"],
  },
  {
    id: "city.suktimati",
    slug: "suktimati",
    kind: "city",
    name: "Śuktimatī",
    englishName: "Suktimati",
    iastName: "Śuktimatī",
    summary: "Capital of Cedi.",
    lat: 24.0,
    lng: 80.5,
    modern: "Bundelkhand (Ken river, traditional)",
    kingdom: "Cedi",
    category: "city",
    importance: 3,
    tags: ["capital"],
  },
  {
    id: "city.viratanagara",
    slug: "viratanagara",
    kind: "city",
    name: "Virāṭanagara",
    englishName: "Viratanagara",
    iastName: "Virāṭanagara",
    summary: "Matsya capital of the thirteenth year.",
    lat: 27.0,
    lng: 75.8,
    modern: "Jaipur / Bairat region (traditional)",
    kingdom: "Matsya",
    category: "city",
    importance: 5,
    tags: ["capital", "pandava"],
    sources: [MB("Virāṭa Parva")],
  },
  {
    id: "city.gaya",
    slug: "gaya",
    kind: "city",
    name: "Gayā",
    englishName: "Gaya",
    iastName: "Gayā",
    summary: "Sacred city of Magadha pilgrimage.",
    lat: 24.78,
    lng: 85.0,
    modern: "Gaya, Bihar",
    kingdom: "Magadha",
    category: "pilgrimage",
    importance: 4,
    tags: ["tirtha"],
    sources: [MB("Vana Parva")],
  },
  {
    id: "city.vaishali",
    slug: "vaishali",
    kind: "city",
    name: "Vaiśālī",
    englishName: "Vaishali",
    iastName: "Vaiśālī",
    summary: "Great city of the Vṛji confederacy.",
    lat: 25.99,
    lng: 85.13,
    modern: "Vaishali, Bihar",
    kingdom: "Vṛji",
    category: "city",
    importance: 4,
    tags: ["capital"],
  },

  // —— East ——
  {
    id: "kingdom.vanga",
    slug: "vanga",
    kind: "kingdom",
    name: "Vaṅga",
    englishName: "Vanga",
    iastName: "Vaṅga",
    summary: "Eastern kingdom of the Bengal delta.",
    lat: 23.5,
    lng: 90.0,
    modern: "Bengal / Bangladesh (traditional)",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.pundra",
    slug: "pundra",
    kind: "kingdom",
    name: "Puṇḍra",
    englishName: "Pundra",
    iastName: "Puṇḍra",
    summary: "Eastern realm north of Vaṅga.",
    lat: 25.0,
    lng: 89.0,
    modern: "North Bengal (traditional)",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.suhma",
    slug: "suhma",
    kind: "kingdom",
    name: "Suhma",
    englishName: "Suhma",
    iastName: "Suhma",
    summary: "Eastern coastal kingdom in digvijaya lists.",
    lat: 22.5,
    lng: 88.0,
    modern: "Southwest Bengal (traditional)",
    category: "kingdom",
    importance: 2,
  },
  {
    id: "kingdom.odra",
    slug: "odra",
    kind: "kingdom",
    name: "Oḍra",
    englishName: "Odra",
    iastName: "Oḍra",
    summary: "Eastern coastal realm (Odisha tract).",
    lat: 20.5,
    lng: 86.0,
    modern: "Odisha (traditional)",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.kalinga",
    slug: "kalinga",
    kind: "kingdom",
    name: "Kaliṅga",
    englishName: "Kalinga",
    iastName: "Kaliṅga",
    summary: "Famous eastern coastal kingdom.",
    lat: 20.0,
    lng: 85.5,
    modern: "Coastal Odisha",
    category: "kingdom",
    importance: 4,
  },
  {
    id: "kingdom.pragjyotisha",
    slug: "pragjyotisha",
    kind: "kingdom",
    name: "Prāgjyotiṣa",
    englishName: "Pragjyotisha",
    iastName: "Prāgjyotiṣa",
    aliases: ["Pragjyotisapura"],
    summary: "Far-eastern kingdom of Bhagadatta.",
    lat: 26.2,
    lng: 91.7,
    modern: "Assam / Guwahati region (traditional)",
    category: "kingdom",
    importance: 4,
    tags: ["bhagadatta"],
    sources: [MB("Sabhā Parva"), MB("Droṇa Parva")],
  },

  // —— West / Gujarat ——
  {
    id: "kingdom.anarta",
    slug: "anarta",
    kind: "kingdom",
    name: "Ānarta",
    englishName: "Anarta",
    iastName: "Ānarta",
    summary: "Saurashtra heartland of the Yadus.",
    lat: 22.3,
    lng: 70.8,
    modern: "Saurashtra, Gujarat",
    kingdom: "Yadu",
    category: "kingdom",
    importance: 4,
    sources: [BP("10"), MB("Mausala Parva")],
  },
  {
    id: "kingdom.surashtra",
    slug: "surashtra",
    kind: "kingdom",
    name: "Surāṣṭra",
    englishName: "Surashtra",
    iastName: "Surāṣṭra",
    summary: "Peninsula kingdom of western Bhārata.",
    lat: 21.5,
    lng: 70.5,
    modern: "Saurashtra peninsula",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.kukura",
    slug: "kukura",
    kind: "kingdom",
    name: "Kukura",
    englishName: "Kukura",
    iastName: "Kukura",
    summary: "Yadu-related western clan territory.",
    lat: 22.8,
    lng: 72.5,
    modern: "Gujarat (traditional)",
    category: "kingdom",
    importance: 2,
  },
  {
    id: "kingdom.aparanta",
    slug: "aparanta",
    kind: "kingdom",
    name: "Aparānta",
    englishName: "Aparanta",
    iastName: "Aparānta",
    summary: "Western coastal lands (Konkan).",
    lat: 18.5,
    lng: 73.0,
    modern: "Konkan coast",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.malava",
    slug: "malava",
    kind: "kingdom",
    name: "Mālava",
    englishName: "Malava",
    iastName: "Mālava",
    summary: "Malwa plateau kingdom near Avanti.",
    lat: 23.5,
    lng: 76.5,
    modern: "Malwa, Madhya Pradesh",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.dasarna",
    slug: "dasarna",
    kind: "kingdom",
    name: "Daśārṇa",
    englishName: "Dasarna",
    iastName: "Daśārṇa",
    summary: "Central kingdom east of Avanti.",
    lat: 23.2,
    lng: 78.5,
    modern: "Eastern MP (traditional)",
    category: "kingdom",
    importance: 3,
  },

  // —— Central / Deccan ——
  {
    id: "city.mahishmati",
    slug: "mahishmati",
    kind: "city",
    name: "Māhiṣmatī",
    englishName: "Mahishmati",
    iastName: "Māhiṣmatī",
    summary: "Narmadā city of Kartavīrya / Haihaya fame.",
    lat: 22.17,
    lng: 75.6,
    modern: "Maheshwar region, MP (traditional)",
    kingdom: "Avanti",
    category: "city",
    importance: 4,
    tags: ["capital"],
    sources: [MB("Vana Parva")],
  },
  {
    id: "kingdom.andhra",
    slug: "andhra",
    kind: "kingdom",
    name: "Andhra",
    englishName: "Andhra",
    iastName: "Āndhra",
    summary: "Deccan kingdom of the Godāvarī–Kṛṣṇā tract.",
    lat: 16.5,
    lng: 80.5,
    modern: "Andhra coastal hinterland",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.dravida",
    slug: "dravida",
    kind: "kingdom",
    name: "Draviḍa",
    englishName: "Dravida",
    iastName: "Draviḍa",
    summary: "Far-southern lands in digvijaya lists.",
    lat: 11.0,
    lng: 78.5,
    modern: "Tamil country (traditional)",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.chola",
    slug: "chola",
    kind: "kingdom",
    name: "Cola",
    englishName: "Chola",
    iastName: "Cola",
    aliases: ["Chola"],
    summary: "Southern coastal kingdom.",
    lat: 11.0,
    lng: 79.5,
    modern: "Coromandel / Tamil Nadu",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.pandya",
    slug: "pandya",
    kind: "kingdom",
    name: "Pāṇḍya",
    englishName: "Pandya",
    iastName: "Pāṇḍya",
    summary: "Far-southern kingdom near the tip.",
    lat: 9.5,
    lng: 77.8,
    modern: "Madurai / southern Tamil Nadu",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.kerala",
    slug: "kerala",
    kind: "kingdom",
    name: "Kerala",
    englishName: "Kerala",
    iastName: "Kerala",
    summary: "Malabar coastal kingdom.",
    lat: 10.5,
    lng: 76.2,
    modern: "Kerala",
    category: "kingdom",
    importance: 3,
  },
  {
    id: "kingdom.karnata",
    slug: "karnata",
    kind: "kingdom",
    name: "Karṇāṭa",
    englishName: "Karnata",
    iastName: "Karṇāṭa",
    summary: "Deccan plateau land in southern lists.",
    lat: 15.0,
    lng: 76.5,
    modern: "Karnataka plateau",
    category: "kingdom",
    importance: 2,
  },

  // —— Cities & sites ——
  {
    id: "city.potana",
    slug: "potana",
    kind: "city",
    name: "Potana",
    englishName: "Potana",
    iastName: "Potana",
    summary: "Aśmaka capital on the Godāvarī.",
    lat: 18.7,
    lng: 77.5,
    modern: "Godavari valley (traditional)",
    kingdom: "Aśmaka",
    category: "city",
    importance: 3,
    tags: ["capital"],
  },
  {
    id: "place.lanka",
    slug: "lanka-atlas",
    kind: "city",
    name: "Laṅkā",
    englishName: "Lanka",
    iastName: "Laṅkā",
    summary: "Island realm south of the tip (epic geography).",
    lat: 7.5,
    lng: 80.5,
    modern: "Sri Lanka (traditional epic placement)",
    category: "city",
    importance: 3,
    tags: ["island"],
    sources: [MB("Vana Parva")],
  },

  // —— Forests / battlefields / ashramas ——
  {
    id: "forest.nandana",
    slug: "nandana",
    kind: "forest",
    name: "Nandana",
    englishName: "Nandana",
    iastName: "Nandana-vana",
    summary: "Celestial grove named in epic geography.",
    lat: 30.5,
    lng: 79.5,
    modern: "Himalayan north (symbolic)",
    category: "forest",
    importance: 2,
  },
  {
    id: "battlefield.jayadratha-vadha",
    slug: "sindhu-battlefield",
    kind: "battlefield",
    name: "Sindhu battlefield",
    englishName: "Sindhu field",
    iastName: "Sindhu-yuddha",
    summary: "Theatre of Jayadratha's wars with the Pāṇḍavas.",
    lat: 27.0,
    lng: 69.0,
    modern: "Indus fringe (traditional)",
    kingdom: "Sindhu",
    category: "battlefield",
    importance: 3,
    sources: [MB("Vana Parva")],
  },
  {
    id: "ashrama.vyasa",
    slug: "vyasa-ashrama",
    kind: "ashrama",
    name: "Vyāsa's āśrama",
    englishName: "Vyasa ashrama",
    iastName: "Vyāsāśrama",
    summary: "Traditional seat of Vyāsa in the north.",
    lat: 30.7,
    lng: 78.5,
    modern: "Himalayan foothills (traditional)",
    category: "ashrama",
    importance: 4,
    sources: [MB("Ādi Parva")],
  },
  {
    id: "ashrama.kanva",
    slug: "kanva-ashrama",
    kind: "ashrama",
    name: "Kaṇva's āśrama",
    englishName: "Kanva ashrama",
    iastName: "Kaṇvāśrama",
    summary: "Āśrama linked to Śakuntalā traditions in epic lore.",
    lat: 27.5,
    lng: 78.0,
    modern: "Upper Gangetic plain (traditional)",
    category: "ashrama",
    importance: 3,
  },
  {
    id: "place.pushkara",
    slug: "pushkara",
    kind: "pilgrimage",
    name: "Puṣkara",
    englishName: "Pushkara",
    iastName: "Puṣkara",
    summary: "Great western tīrtha of pilgrimage lists.",
    lat: 26.49,
    lng: 74.55,
    modern: "Pushkar, Rajasthan",
    category: "pilgrimage",
    importance: 4,
    tags: ["tirtha"],
    sources: [MB("Vana Parva")],
  },
  {
    id: "place.badari",
    slug: "badari-tirtha",
    kind: "pilgrimage",
    name: "Badarī",
    englishName: "Badari",
    iastName: "Badarī",
    summary: "Northern tīrtha of Nara–Nārāyaṇa fame.",
    lat: 30.74,
    lng: 79.49,
    modern: "Badrinath, Uttarakhand",
    category: "pilgrimage",
    importance: 5,
    tags: ["tirtha"],
    sources: [MB("Vana Parva"), BG("11")],
  },
  {
    id: "mountain.meru",
    slug: "meru",
    kind: "mountain",
    name: "Meru",
    englishName: "Meru",
    iastName: "Meru",
    summary: "Cosmic mountain of northern sacred geography.",
    lat: 31.5,
    lng: 80.0,
    modern: "Himalayan / cosmological north (symbolic)",
    category: "mountain",
    importance: 4,
  },
  {
    id: "mountain.gandhamadana",
    slug: "gandhamadana",
    kind: "mountain",
    name: "Gandhamādana",
    englishName: "Gandhamadana",
    iastName: "Gandhamādana",
    summary: "Mountain of Bhīma's journeys and divine flora.",
    lat: 30.9,
    lng: 79.2,
    modern: "Garhwal Himalaya (traditional)",
    category: "mountain",
    importance: 4,
    sources: [MB("Vana Parva")],
  },
  {
    id: "river.sarayu",
    slug: "sarayu",
    kind: "river",
    name: "Sarayū",
    englishName: "Sarayu",
    iastName: "Sarayū",
    summary: "River of Kosala in epic geography.",
    lat: 27.2,
    lng: 82.2,
    modern: "Ghaghara / Sarayu system",
    category: "river",
    importance: 4,
  },
  {
    id: "river.shipra",
    slug: "shipra",
    kind: "river",
    name: "Śiprā",
    englishName: "Shipra",
    iastName: "Śiprā",
    summary: "River of Ujjayinī.",
    lat: 23.2,
    lng: 75.8,
    modern: "Shipra, Madhya Pradesh",
    kingdom: "Avanti",
    category: "river",
    importance: 3,
  },
  {
    id: "river.kaveri",
    slug: "kaveri",
    kind: "river",
    name: "Kāverī",
    englishName: "Kaveri",
    iastName: "Kāverī",
    summary: "Great southern river.",
    lat: 11.5,
    lng: 77.5,
    modern: "Kaveri river",
    category: "river",
    importance: 3,
  },
  {
    id: "river.krishna",
    slug: "krishna-river",
    kind: "river",
    name: "Kṛṣṇā",
    englishName: "Krishna River",
    iastName: "Kṛṣṇā",
    summary: "Deccan river of southern digvijaya geography.",
    lat: 16.5,
    lng: 78.0,
    modern: "Krishna river",
    category: "river",
    importance: 3,
  },
  {
    id: "place.kedara",
    slug: "kedara",
    kind: "pilgrimage",
    name: "Kedāra",
    englishName: "Kedara",
    iastName: "Kedāra",
    summary: "Himalayan tīrtha of Śiva fame in pilgrimage lists.",
    lat: 30.73,
    lng: 79.07,
    modern: "Kedarnath, Uttarakhand",
    category: "pilgrimage",
    importance: 4,
    tags: ["tirtha"],
    sources: [MB("Vana Parva")],
  },
  {
    id: "place.kailasa",
    slug: "kailasa",
    kind: "mountain",
    name: "Kailāsa",
    englishName: "Kailasa",
    iastName: "Kailāsa",
    summary: "Sacred northern mountain of divine geography.",
    lat: 31.07,
    lng: 81.31,
    modern: "Mount Kailash region (traditional)",
    category: "mountain",
    importance: 5,
  },
  {
    id: "city.sakala",
    slug: "sakala",
    kind: "city",
    name: "Śākala",
    englishName: "Sakala",
    iastName: "Śākala",
    summary: "Madra capital in epic geography.",
    lat: 32.5,
    lng: 74.5,
    modern: "Sialkot region (traditional)",
    kingdom: "Madra",
    category: "city",
    importance: 3,
    tags: ["capital"],
  },
  {
    id: "place.hastinapura-ghat",
    slug: "hastinapura-ghat",
    kind: "pilgrimage",
    name: "Hastināpura ghats",
    englishName: "Hastinapura ghats",
    iastName: "Hastināpura-ghāṭa",
    summary: "Riverfront of the Kuru capital.",
    lat: 29.16,
    lng: 78.02,
    modern: "Near Meerut, UP",
    kingdom: "Kuru",
    category: "pilgrimage",
    importance: 3,
  },
];

export const DENSE_ATLAS_ENTITIES: Entity[] = ROWS.map(fromRow);

/** No new person↔place edges here — citation graph already covers core links. */
export const DENSE_ATLAS_RELATIONS: Array<{
  id: string;
  fromId: string;
  toId: string;
  type: string;
  confidence: "verified" | "traditional" | "variant";
  sources: Cite[];
  note?: string;
}> = [];
