/**
 * 16 Mahajanapadas + additional Mahābhārata / Gītā places for Atlas.
 */
import { makeRelationId } from "./helpers.mts";

type Cite = { work: string; section?: string; chapter?: string; note?: string };
type AtlasMeta = {
  latitude: number;
  longitude: number;
  modernLocation: string;
  kingdom?: string;
  scripturalSignificance?: string;
  atlasCategory?: string;
};

type Entity = {
  id: string;
  slug: string;
  kind: string;
  name: string;
  englishName: string;
  iastName: string;
  aliases: string[];
  summary: string;
  description: string;
  primaryScripture: string;
  scriptureSources: Cite[];
  tags: string[];
  categories: string[];
  importance: number;
  seo: { title?: string };
  atlas: AtlasMeta;
  status: "published";
  schemaVersion: number;
  era: string;
  variantTraditions: [];
};

const MB = (parva: string): Cite => ({ work: "Mahābhārata", section: parva });
const BP = (sk: string): Cite => ({ work: "Bhāgavata Purāṇa", section: `Skandha ${sk}` });
const BG = (ch: string): Cite => ({ work: "Bhagavad Gītā", chapter: ch });

function e(p: Omit<Entity, "status" | "schemaVersion" | "variantTraditions" | "era"> & { era?: string }): Entity {
  return { status: "published", schemaVersion: 1, era: p.era ?? "dvapara-yuga", variantTraditions: [], ...p };
}

export const MAHAJANAPADA_ENTITIES: Entity[] = [
  e({ id: "kingdom.kuru", slug: "kuru", kind: "kingdom", name: "Kuru", englishName: "Kuru", iastName: "Kuru", aliases: ["Kurujangala"], summary: "Heartland of the Kauravas and Pāṇḍavas.", description: "The Kuru realm is the political centre of the Mahābhārata — Hastināpura, Indraprastha and Kurukṣetra.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Ādi Parva"), BG("1")], tags: ["mahajanapada"], categories: ["kingdom"], importance: 5, seo: { title: "Kuru" }, atlas: { latitude: 29.5, longitude: 77.2, modernLocation: "Haryana / western Uttar Pradesh", kingdom: "Kuru", scripturalSignificance: "Yamunā / Sarasvatī heartland.", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.kosala", slug: "kosala", kind: "kingdom", name: "Kosala", englishName: "Kosala", iastName: "Kosala", aliases: [], summary: "Northern kingdom on the Sarayū.", description: "Kosala is tied to the Sarayū river in epic geography.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["mahajanapada"], categories: ["kingdom"], importance: 4, seo: { title: "Kosala" }, atlas: { latitude: 27.0, longitude: 82.5, modernLocation: "Eastern Uttar Pradesh (Awadh)", kingdom: "Kosala", scripturalSignificance: "Sarayū river.", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.anga", slug: "anga", kind: "kingdom", name: "Aṅga", englishName: "Anga", iastName: "Aṅga", aliases: ["Anga"], summary: "Eastern kingdom of Karṇa; capital Campā.", description: "Aṅga is granted to Karṇa; Campā stands on the Gaṅgā.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Ādi Parva")], tags: ["mahajanapada", "karna"], categories: ["kingdom"], importance: 4, seo: { title: "Aṅga" }, atlas: { latitude: 25.0, longitude: 87.0, modernLocation: "Bhagalpur region, Bihar", kingdom: "Aṅga", scripturalSignificance: "Gaṅgā / Campā.", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.vajji", slug: "vajji", kind: "kingdom", name: "Vṛji", englishName: "Vajji", iastName: "Vṛji", aliases: ["Vajji"], summary: "Confederacy north of the Gaṅgā.", description: "Vṛji lies north of the Gaṅgā; Vaiśālī is its great city.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["mahajanapada"], categories: ["kingdom"], importance: 3, seo: { title: "Vṛji" }, atlas: { latitude: 26.0, longitude: 85.2, modernLocation: "North Bihar (Vaishali)", kingdom: "Vṛji", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.malla", slug: "malla", kind: "kingdom", name: "Malla", englishName: "Malla", iastName: "Malla", aliases: [], summary: "Realm near the Little Gandak.", description: "Malla is counted among the sixteen great realms of northern Bhārata.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["mahajanapada"], categories: ["kingdom"], importance: 3, seo: { title: "Malla" }, atlas: { latitude: 26.6, longitude: 83.8, modernLocation: "Gandak region, eastern UP / Bihar", kingdom: "Malla", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.cedi", slug: "cedi", kind: "kingdom", name: "Cedi", englishName: "Cedi", iastName: "Cedi", aliases: ["Chedi"], summary: "Kingdom of Śiśupāla; Ken river region.", description: "Cedi is Śiśupāla's realm, opposed to Kṛṣṇa at the Rājasūya.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["mahajanapada"], categories: ["kingdom"], importance: 4, seo: { title: "Cedi" }, atlas: { latitude: 24.2, longitude: 80.3, modernLocation: "Bundelkhand (Ken river)", kingdom: "Cedi", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.vatsa", slug: "vatsa", kind: "kingdom", name: "Vatsa", englishName: "Vatsa", iastName: "Vatsa", aliases: [], summary: "Yamunā kingdom; capital Kauśāmbī.", description: "Vatsa is a Yamunā-side Mahājanapada with capital Kauśāmbī.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["mahajanapada"], categories: ["kingdom"], importance: 4, seo: { title: "Vatsa" }, atlas: { latitude: 25.5, longitude: 81.3, modernLocation: "Near Prayagraj (Kausambi)", kingdom: "Vatsa", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.surasena", slug: "surasena", kind: "kingdom", name: "Śūrasena", englishName: "Surasena", iastName: "Śūrasena", aliases: ["Surasena"], summary: "Mathurā region on the Yamunā.", description: "Śūrasena is the Mathurā heartland of early Yadu history.", primaryScripture: "Bhāgavata Purāṇa", scriptureSources: [BP("10"), MB("Sabhā Parva")], tags: ["mahajanapada", "yadu"], categories: ["kingdom"], importance: 5, seo: { title: "Śūrasena" }, atlas: { latitude: 27.4, longitude: 77.5, modernLocation: "Mathura, Uttar Pradesh", kingdom: "Śūrasena", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.assaka", slug: "assaka", kind: "kingdom", name: "Aśmaka", englishName: "Assaka", iastName: "Aśmaka", aliases: ["Assaka"], summary: "Deccan Mahājanapada on the Godāvarī.", description: "Aśmaka is the southern Mahājanapada of the Godāvarī valley.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["mahajanapada"], categories: ["kingdom"], importance: 3, seo: { title: "Aśmaka" }, atlas: { latitude: 18.8, longitude: 78.0, modernLocation: "Godavari valley", kingdom: "Aśmaka", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.avanti", slug: "avanti", kind: "kingdom", name: "Avanti", englishName: "Avanti", iastName: "Avanti", aliases: [], summary: "Malwa kingdom; capital Ujjayinī.", description: "Avanti is the western realm of Ujjayinī on the Śiprā.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Vana Parva")], tags: ["mahajanapada"], categories: ["kingdom"], importance: 4, seo: { title: "Avanti" }, atlas: { latitude: 23.2, longitude: 75.8, modernLocation: "Ujjain, Madhya Pradesh", kingdom: "Avanti", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.kamboja", slug: "kamboja", kind: "kingdom", name: "Kāmboja", englishName: "Kamboja", iastName: "Kāmboja", aliases: ["Kamboja"], summary: "Northwestern highland realm.", description: "Kāmboja is associated with the Hindukush–Indus frontier in digvijaya lists.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["mahajanapada"], categories: ["kingdom"], importance: 3, seo: { title: "Kāmboja" }, atlas: { latitude: 35.0, longitude: 71.5, modernLocation: "Hindukush / NW frontier", kingdom: "Kāmboja", atlasCategory: "kingdom" } }),
  e({ id: "kingdom.vidarbha", slug: "vidarbha", kind: "kingdom", name: "Vidarbha", englishName: "Vidarbha", iastName: "Vidarbha", aliases: [], summary: "Deccan kingdom of Rukmiṇī.", description: "Vidarbha is Rukmiṇī's homeland in the Bhāgavata.", primaryScripture: "Bhāgavata Purāṇa", scriptureSources: [BP("10")], tags: ["rukmini"], categories: ["kingdom"], importance: 4, seo: { title: "Vidarbha" }, atlas: { latitude: 20.5, longitude: 78.5, modernLocation: "Vidarbha, Maharashtra", kingdom: "Vidarbha", atlasCategory: "kingdom" } }),
  e({ id: "city.taxila", slug: "taxila", kind: "city", name: "Takṣaśilā", englishName: "Taxila", iastName: "Takṣaśilā", aliases: ["Takshashila"], summary: "Capital of Gāndhāra.", description: "Takṣaśilā is the capital of Gāndhāra, homeland of Gāndhārī and Śakuni.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Ādi Parva")], tags: ["capital"], categories: ["city"], importance: 4, seo: { title: "Takṣaśilā" }, atlas: { latitude: 33.74, longitude: 72.78, modernLocation: "Taxila, Pakistan", kingdom: "Gāndhāra", atlasCategory: "city" } }),
  e({ id: "city.kausambi", slug: "kausambi", kind: "city", name: "Kauśāmbī", englishName: "Kausambi", iastName: "Kauśāmbī", aliases: [], summary: "Capital of Vatsa.", description: "Kauśāmbī is the Vatsa capital on the Yamunā.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["capital"], categories: ["city"], importance: 4, seo: { title: "Kauśāmbī" }, atlas: { latitude: 25.34, longitude: 81.39, modernLocation: "Near Prayagraj, UP", kingdom: "Vatsa", atlasCategory: "city" } }),
  e({ id: "city.ujjayini", slug: "ujjayini", kind: "city", name: "Ujjayinī", englishName: "Ujjain", iastName: "Ujjayinī", aliases: ["Ujjain"], summary: "Capital of Avanti.", description: "Ujjayinī is the great city of Avanti on the Śiprā.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Vana Parva")], tags: ["capital", "pilgrimage"], categories: ["city", "pilgrimage"], importance: 5, seo: { title: "Ujjayinī" }, atlas: { latitude: 23.18, longitude: 75.78, modernLocation: "Ujjain, Madhya Pradesh", kingdom: "Avanti", atlasCategory: "city" } }),
  e({ id: "city.rajagriha", slug: "rajagriha", kind: "city", name: "Rājagṛha", englishName: "Rajagriha", iastName: "Rājagṛha", aliases: ["Rajgir", "Girivraja"], summary: "Hill capital of Magadha.", description: "Rājagṛha is Jarāsandha's fortified capital.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["capital"], categories: ["city"], importance: 5, seo: { title: "Rājagṛha" }, atlas: { latitude: 25.03, longitude: 85.42, modernLocation: "Rajgir, Bihar", kingdom: "Magadha", atlasCategory: "city" } }),
  e({ id: "city.pataliputra", slug: "pataliputra", kind: "city", name: "Pāṭaliputra", englishName: "Pataliputra", iastName: "Pāṭaliputra", aliases: ["Patna"], summary: "Later Magadha capital.", description: "Pāṭaliputra at the Gaṅgā–Śoṇa confluence.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["capital"], categories: ["city"], importance: 4, seo: { title: "Pāṭaliputra" }, atlas: { latitude: 25.6, longitude: 85.1, modernLocation: "Patna, Bihar", kingdom: "Magadha", atlasCategory: "city" } }),
  e({ id: "city.champa", slug: "champa", kind: "city", name: "Campā", englishName: "Champa", iastName: "Campā", aliases: [], summary: "Capital of Aṅga.", description: "Campā is the Aṅga capital on the Gaṅgā.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Vana Parva")], tags: ["capital"], categories: ["city"], importance: 3, seo: { title: "Campā" }, atlas: { latitude: 25.25, longitude: 87.0, modernLocation: "Near Bhagalpur, Bihar", kingdom: "Aṅga", atlasCategory: "city" } }),
  e({ id: "city.varanavata", slug: "varanavata", kind: "city", name: "Vāraṇāvata", englishName: "Varanavata", iastName: "Vāraṇāvata", aliases: [], summary: "Town of the lacquer-house plot.", description: "At Vāraṇāvata the Pāṇḍavas are nearly burned in the house of lac.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Ādi Parva")], tags: ["pandava"], categories: ["city"], importance: 4, seo: { title: "Vāraṇāvata" }, atlas: { latitude: 29.6, longitude: 77.6, modernLocation: "Near Meerut region (traditional)", kingdom: "Kuru", atlasCategory: "city" } }),
  e({ id: "city.ekachakra", slug: "ekachakra", kind: "city", name: "Ekacakra", englishName: "Ekachakra", iastName: "Ekacakra", aliases: [], summary: "Where Bhīma slays Baka.", description: "Ekacakra is where Bhīma destroys the asura Baka.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Ādi Parva")], tags: ["bhima"], categories: ["city"], importance: 3, seo: { title: "Ekacakra" }, atlas: { latitude: 26.5, longitude: 82.0, modernLocation: "Eastern UP (traditional)", atlasCategory: "city" } }),
  e({ id: "city.upaplavya", slug: "upaplavya", kind: "city", name: "Upaplavya", englishName: "Upaplavya", iastName: "Upaplavya", aliases: [], summary: "Matsya base before the war.", description: "Upaplavya is the Pāṇḍava seat of embassies before Kurukṣetra.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Udyoga Parva")], tags: ["pandava"], categories: ["city"], importance: 4, seo: { title: "Upaplavya" }, atlas: { latitude: 26.7, longitude: 76.0, modernLocation: "Matsya / Rajasthan (traditional)", kingdom: "Matsya", atlasCategory: "city" } }),
  e({ id: "place.prabhasa", slug: "prabhasa", kind: "pilgrimage", name: "Prabhāsa", englishName: "Prabhasa", iastName: "Prabhāsa", aliases: ["Somnath"], summary: "Shore of the Yadu end.", description: "Prabhāsa is linked to the Mausala destruction of the Yadus.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Mausala Parva")], tags: ["yadu"], categories: ["pilgrimage"], importance: 4, seo: { title: "Prabhāsa" }, atlas: { latitude: 20.89, longitude: 70.4, modernLocation: "Somnath, Gujarat", kingdom: "Yadu", atlasCategory: "pilgrimage" } }),
  e({ id: "place.prayaga", slug: "prayaga", kind: "pilgrimage", name: "Prayāga", englishName: "Prayaga", iastName: "Prayāga", aliases: ["Prayagraj"], summary: "Gaṅgā–Yamunā confluence.", description: "Prayāga is the foremost saṅgama tīrtha of epic pilgrimage lists.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Vana Parva")], tags: ["tirtha"], categories: ["pilgrimage"], importance: 5, seo: { title: "Prayāga" }, atlas: { latitude: 25.43, longitude: 81.85, modernLocation: "Prayagraj, Uttar Pradesh", atlasCategory: "pilgrimage" } }),
  e({ id: "place.haridwar", slug: "haridwar", kind: "pilgrimage", name: "Gaṅgādvāra", englishName: "Haridwar", iastName: "Gaṅgādvāra", aliases: ["Haridwar"], summary: "Where Gaṅgā enters the plains.", description: "Gaṅgādvāra is the northern gate of the Gaṅgā.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Vana Parva")], tags: ["tirtha"], categories: ["pilgrimage"], importance: 4, seo: { title: "Gaṅgādvāra" }, atlas: { latitude: 29.95, longitude: 78.16, modernLocation: "Haridwar, Uttarakhand", atlasCategory: "pilgrimage" } }),
  e({ id: "forest.khandava", slug: "khandava", kind: "forest", name: "Khāṇḍava Forest", englishName: "Khandava", iastName: "Khāṇḍava-vana", aliases: [], summary: "Forest burned for Indraprastha.", description: "Arjuna and Kṛṣṇa aid Agni in the Khāṇḍava fire.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Ādi Parva")], tags: ["arjuna"], categories: ["forest"], importance: 4, seo: { title: "Khāṇḍava" }, atlas: { latitude: 28.5, longitude: 77.1, modernLocation: "Delhi / Yamuna tract", kingdom: "Kuru", atlasCategory: "forest" } }),
  e({ id: "city.kundinapura", slug: "kundinapura", kind: "city", name: "Kuṇḍinapura", englishName: "Kundinapura", iastName: "Kuṇḍinapura", aliases: [], summary: "Vidarbha capital; Rukmiṇī's city.", description: "Kuṇḍinapura is where Kṛṣṇa wins Rukmiṇī.", primaryScripture: "Bhāgavata Purāṇa", scriptureSources: [BP("10")], tags: ["rukmini"], categories: ["city"], importance: 3, seo: { title: "Kuṇḍinapura" }, atlas: { latitude: 20.7, longitude: 77.0, modernLocation: "Vidarbha (traditional)", kingdom: "Vidarbha", atlasCategory: "city" } }),
  e({ id: "river.narmada", slug: "narmada", kind: "river", name: "Narmadā", englishName: "Narmada", iastName: "Narmadā", aliases: ["Narmada"], summary: "Great west-flowing central river.", description: "Narmadā bounds northern and southern landscapes in epic geography.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Vana Parva")], tags: ["river"], categories: ["river"], importance: 4, seo: { title: "Narmadā" }, atlas: { latitude: 22.0, longitude: 76.0, modernLocation: "Narmada river, central India", atlasCategory: "river" } }),
  e({ id: "river.godavari", slug: "godavari", kind: "river", name: "Godāvarī", englishName: "Godavari", iastName: "Godāvarī", aliases: [], summary: "Great Deccan river.", description: "Godāvarī is the principal river of Aśmaka and the Deccan.", primaryScripture: "Mahābhārata", scriptureSources: [MB("Sabhā Parva")], tags: ["river"], categories: ["river"], importance: 4, seo: { title: "Godāvarī" }, atlas: { latitude: 18.5, longitude: 78.0, modernLocation: "Godavari river", atlasCategory: "river" } }),
];

export const MAHAJANAPADA_RELATIONS = [
  { id: makeRelationId("person.karna", "king-of", "kingdom.anga"), fromId: "person.karna", toId: "kingdom.anga", type: "king-of", confidence: "verified" as const, sources: [MB("Ādi Parva")] },
  { id: makeRelationId("person.arjuna", "fought-in", "forest.khandava"), fromId: "person.arjuna", toId: "forest.khandava", type: "fought-in", confidence: "verified" as const, sources: [MB("Ādi Parva")] },
  { id: makeRelationId("person.krishna", "visited", "place.prabhasa"), fromId: "person.krishna", toId: "place.prabhasa", type: "visited", confidence: "traditional" as const, sources: [MB("Mausala Parva")] },
];
